Repository SU-SWS/saa_alumni, pull requests merged in 2021-10, with the labels that each got.

#200 ADAPT-3811, ADAPT-3727: Filter page styles, Hero finetune
  src/components/cards/TripCard/TripCard.jsx
  src/components/cards/TripCard/TripCard.styles.js
  src/components/composite/HeroImage/HeroImage.jsx
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/composite/Pagination/Pagination.styles.js
  src/components/composite/TripFilterList/TripFilterList.styles.js
  src/components/identity/global-header/GlobalHeader.jsx
  src/components/media/fullWidthImage.js
  src/components/navigation/SAAMainNav/SAAMainMenuGroup.jsx
  src/components/navigation/SAAMainNav/SAAMainNav.jsx
  src/components/navigation/UtilityNav.jsx
  src/components/navigation/mainMenuGroup.js
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/page-types/TripPage/TripPageHeroSection.styles.js
  src/components/simple/Chip/Chip.styles.js
  src/components/simple/Date/Date.jsx
  src/components/simple/Date/Date.styles.js
  src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
  src/tailwind/plugins/theme/colors.js
  src/utilities/convertAspectRatio.js
Labels: size/m

#203 ADAPT-3826: Update redirect for home
  static/_redirects
Labels: size/xs

#193 ADAPT-3779: More a11y fixes
  src/components/cards/ctaCard.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaLink.js
  src/components/identity/masthead.js
  src/components/layout/modal.js
  src/components/search/openSearchModalButton.js
  src/components/search/searchAutocomplete.js
  src/components/search/searchField.js
  src/components/search/searchFieldModal.js
  src/components/search/searchModal.js
Labels: size/s

#230 ADAPT-3957: Accommodation changes and add meal options to Itinerary item
  src/components/composite/itineraryItem.js
Labels: size/s, feature
