Repository SU-SWS/saa_alumni, pull requests merged in 2021-08, with the labels that each got.

#104 ADAPT-3104, ADAPT-3090: Fixup for main nav hamburger button hover/focus state and desktop parent item; hero headline mobile font size
  src/components/composite/hero.js
  src/components/navigation/mainMenuGroup.js
  src/components/navigation/mainNav.js
Labels: size/xs

#105 ADAPT-3107: Reduce vertical gutter of Grid component
  src/components/layout/grid.js
Labels: size/xs

#108 ADAPT-3108: Added spacing between filters and content on search page
  src/components/page-types/searchPage.js
Labels: size/xs

#95 ADAPT-2398: Created Vertical Nav Component and implementation.
  gatsby-config.js
  package-lock.json
  src/components/components.js
  src/components/navigation/verticalNav.js
  src/components/navigation/verticalNavItem.js
  src/components/navigation/verticalNavWrapper.js
  src/components/page-types/basicPage.js
  src/components/partials/basicContentLeftSidebar.js
  src/tailwind/plugins/theme/colors.js
Labels: size/xl

#112 ADAPT-3122: Remove fw semibold for the search input
  src/components/page-types/searchPage.js
  src/components/search/searchFieldModal.js
Labels: size/xs

#111 ADAPT-3132: Change search field container zindex
  src/components/page-types/searchPage.js
Labels: size/xs

#113 ADAPT-3112: Rotate search icon
  src/components/page-types/searchPage.js
Labels: size/xs

#107 ADAPT-3092: Wysiwyg center text option
  src/components/simple/wysiwyg.js
Labels: size/xs

#110 ADAPT-3110: Stretch container to full width when search results are n…
  src/components/page-types/searchPage.js
Labels: size/xs

#109 ADAPT-3115: Refactored facets implementation to allow for multiple values.
  src/components/page-types/searchPage.js
Labels: size/xs

#80 ADAPT-2989: Cards and CTA button tweaks
  src/components/cards/basicCard.js
  src/components/cards/ctaCard.js
  src/components/cards/eventCard.js
  src/components/cards/storyCard.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkCardView.js
  src/components/content-types/story/storyCardView.js
  src/components/content-types/story/storyPageView.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaLink.js
  src/components/simple/heroIcon.js
  src/components/simple/tabLabel.js
  src/utilities/richTextRenderer.js
  src/utilities/sbLink.js
Labels: size/xs

#106 ADAPT-3107: Large grid gap option, Section title font size option
  src/components/layout/grid.js
  src/components/layout/section.js
Labels: size/xs

#114 ADAPT-3103: Updated unique ID for embed cards, to avoid error.
  src/components/cards/embedCard.js
Labels: size/xs

#117 ADAPT-3117: Change cursor for search checkboxes
  src/components/search/searchFacet.js
Labels: size/xs

#115 ADAPT-3152: Remove internal link icon for icon cards
  src/components/cards/ctaCard.js
  src/components/cards/iconCard.js
Labels: size/xs

#120 ADAPT-3114: Updated autocomplete styling to match modal version.
  src/components/page-types/searchPage.js
Labels: size/xs

#91 ADAPT-2728: Replacing intro text with emptySearchText if input empty
  src/components/search/searchFieldModal.js
  src/components/search/searchModal.js
Labels: size/xs

#121 ADAPT-3120: Removed outline from search field.
  src/components/page-types/searchPage.js
Labels: size/xs

#122 ADAPT-2989: More card tweaks
  src/components/cards/eventCard.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkCardView.js
  src/components/content-types/story/storyCardView.js
  src/components/simple/dateBlock.js
  src/components/simple/tabLabel.js
Labels: size/xs

#123 ADAPT-000: Change static graphql query from ID to slug for multi environment.
  src/components/search/searchModal.js
Labels: size/xs

#99 ADAPT-2670: Search mobile theming
  src/components/page-types/searchPage.js
  src/components/search/searchFacet.js
  src/components/search/searchPager.js
  src/components/search/searchResults.js
Labels: size/m

#118 ADAPT-3117: Scrollable modal
  src/components/layout/modal.js
  src/components/search/searchModal.js
Labels: size/xs

#124 ADAPT-3118: Add underline and correct icons
  src/components/search/searchResults.js
Labels: size/xs

#125 ADAPT-3157: Remove package react-id-generator and its usage
  package-lock.json
  package.json
  src/components/composite/poster.js
  src/components/layout/section.js
  src/components/page-types/searchPage.js
  src/components/partials/layout.js
  src/components/simple/wysiwyg.js
Labels: size/xs

#128 ADAPT-3106: Added code to support no-index parameter in page metatags and sitemap.
  gatsby-config.js
  gatsby-node.js
  src/components/page-types/basicPage.js
Labels: size/xs

#126 ADAPT-3141: Fix search results image aspct ratio
  src/components/search/searchResults.js
Labels: size/xs

#131 ADAPT-3185 Adjust alert link colors
  src/components/composite/alert.js
  src/styles/alert.css
Labels: size/xs

#130 ADAPT-3156 Update SimpleImage component to use FullWidthImage component for edge-to-edge
  src/components/media/simpleImage.js
Labels: size/xs

#127 ADAPT-3187: Fix title encoding issue for search results
  src/components/search/searchResults.js
Labels: size/xs

#134 ADAPT-3167: Use TW form plugin for checkbox styling
  gatsby-ssr.js
  package-lock.json
  package.json
  src/components/page-types/searchPage.js
  src/components/search/searchFacet.js
  src/components/search/searchFieldModal.js
  src/tailwind/plugins/components/checkbox/custom-checkbox.js
  static/images/checked-icon.svg
  tailwind.config.js
Labels: size/xs

#129 ADAPT-3158: Add active state to main nav; utility nav style tweak
  src/components/identity/masthead.js
  src/components/navigation/mainMenuGroup.js
  src/components/navigation/mainNavItem.js
Labels: size/xs

#68 Adapt 2726 smart focus
  src/components/cards/basicCard.js
  src/components/composite/hero.js
  src/components/composite/poster.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkCardView.js
  src/components/content-types/perk/perkPageView.js
  src/components/content-types/story/storyCardView.js
  src/components/content-types/story/storyPageView.js
  src/components/media/cardImage.js
  src/components/media/circularImage.js
  src/components/media/fullWidthImage.js
  src/utilities/transformImage.js
Labels: size/xs

#136 ADAPT-2945: Add skiplink to section menu
  src/components/navigation/mainMenuGroup.js
  src/components/navigation/verticalNav.js
  src/components/page-types/basicPage.js
  src/components/partials/basicContentLeftSidebar.js
  src/components/partials/header.js
Labels: size/xs

#133 ADAPT-2670: Created alternative pager for mobile.
  src/components/search/searchPager.js
  src/utilities/buildPager.js
Labels: size/xs

#135 ADAPT-3167: Add bottom spacing to keyword search banner; CTA link color transition; search page grid
  src/components/cta/ctaLink.js
  src/components/page-types/searchPage.js
  src/components/search/searchKeywordBanner.js
  src/components/search/searchResults.js
Labels: size/xs

#116 ADAPT-3124: Search styles
  src/components/layout/modal.js
  src/components/page-types/searchPage.js
  src/components/search/searchField.js
  src/components/search/searchFieldModal.js
Labels: size/xs

#132 ADAPT-3142: Search filters checkbox state styles
  src/components/page-types/searchPage.js
  src/components/search/searchFacet.js
Labels: size/xs

#141 ADAPT-000: Fixup CTA Link icon color
  src/components/cta/ctaLink.js
  src/utilities/dataSource.js
Labels: size/xs

#140 ADAPT-3106: Make noindex and canonical tags mutually exclusive.
  src/components/page-types/basicPage.js
  src/components/partials/seo.js
Labels: size/xs

#143 ADAPT-3143: Search modal styles
  src/components/layout/modal.js
  src/components/page-types/searchPage.js
  src/components/search/searchField.js
  src/components/search/searchFieldModal.js
  src/components/search/searchModal.js
  src/components/search/searchNoResults.js
  src/components/search/searchSuggestions.js
  src/components/simple/linkList.js
Labels: size/s

#144 ADAPT-000: Basic Card fixup
  src/components/cards/basicCard.js
Labels: size/xs

#146 ADAPT-3222: Remove autoselect behavior on search suggestions.
  src/components/search/searchField.js
Labels: size/xs
