Repository SU-SWS/saa_alumni, pull requests merged in 2021-09, with the labels that each got.

#145 ADAPT-3221: Search page style tweaks; section nav tweaks
  src/components/navigation/verticalNav.js
  src/components/navigation/verticalNavItem.js
  src/components/navigation/verticalNavWrapper.js
  src/components/page-types/searchPage.js
  src/components/search/searchAutocomplete.js
  src/components/search/searchFacet.js
  src/components/search/searchFieldModal.js
  src/components/search/searchPager.js
  src/components/search/searchResults.js
Labels: size/s

#147 ADAPT-000: hotfix | Grid fixup
  src/components/layout/grid.js
Labels: size/xs

#149 ADAPT-3235: Add support for newer FA icons
  package-lock.json
  package.json
  src/components/cards/iconCard.js
  src/components/cta/ctaLink.js
  src/components/simple/faIcon.js
Labels: size/s

#150 ADAPT-3259: Itinerary component
  src/components/components.js
  src/components/composite/itinerary.js
  src/components/composite/itineraryItem.js
  src/components/media/cardImage.js
  src/components/simple/dateBlock.js
Labels: size/s

#154 ADAPT-3254 | @mattanglin | basic trip entity
  package-lock.json
  package.json
  storyblok/README.md
  storyblok/components.118608.json
  storyblok/presets.118608.json
Labels: size/xl

#156 ADAPT-3305: Added x-frame-options header.
  netlify.toml
Labels: size/xs

#152 ADAPT-3209: Add option to hide "scroll to explore" link on hero banner
  src/components/composite/hero.js
Labels: size/xs

#158 ADAPT-3305: Add x-frame-options headers.
  netlify.toml
Labels: size/xs

#157 ADAPT-3281: Extract reusable GradientCard and create Collection Card component
  src/components/cards/collectionCard.js
  src/components/cards/collectionCardHorizontal.js
  src/components/cards/gradientCard.js
  src/components/components.js
  src/components/content-types/perk/perkCardView.js
  src/components/media/cardImage.js
Labels: size/m

#159 ADAPT-3255 | trip page layout
  gatsby-node.js
  package-lock.json
  package.json
  src/components/components.js
  src/components/page-types/TripPage.jsx
Labels: size/xs

#161 ADAPT-000: Update tailwind.config.js
  tailwind.config.js
Labels: size/xs

#165 ADAPT-000 Embed Card Width Fixup
  src/components/cards/embedCard.js
Labels: size/xs

#148 ADAPT-3235: Add PRO FontAwesome icon support
  .github/workflows/eslint.yml
  .gitignore
  .npmrc
  README.md
  example.env
  gatsby-config.js
  package-lock.json
  package.json
  src/components/cards/iconCard.js
  src/components/cta/ctaLink.js
  src/components/simple/faIcon.js
  src/components/simple/linkList.js
Labels: size/s

#163 ADAPT-3263 | @mattanglin | trip card
  .eslintrc
  gatsby-config.js
  src/components/cards/TripCard/TripCard.jsx
  src/components/cards/TripCard/TripCard.styles.js
  src/components/components.js
  src/components/content-types/perk/perkCardView.js
  src/components/page-types/TripPage.jsx
  src/components/simple/Date/Date.jsx
  src/components/simple/Date/Date.styles.js
  src/components/simple/Date/getDate.js
  src/components/storyblok/README.md
  src/components/storyblok/tripCard.jsx
  src/tailwind/plugins/theme/colors.js
  src/types/HeadingLevelType.js
  src/types/TripType.js
  storyblok/components.118608.json
  storyblok/presets.118608.json
Labels: size/l

#155 ADAPT-2999: Skiplink adjustments
  gatsby-config.js
  src/components/composite/hero.js
  src/components/media/embedVideo.js
  src/components/page-types/basicPage.js
  src/components/partials/basicContentLeftSidebar.js
  src/components/partials/header.js
Labels: size/xs

#170 ADAPT-3715: Misc search a11y fixes
  src/components/composite/hero.js
  src/components/cta/ctaLink.js
  src/components/identity/localFooter.js
  src/components/page-types/searchPage.js
  src/components/partials/header.js
  src/components/search/searchField.js
  src/components/search/searchFieldModal.js
  src/components/search/searchModal.js
  src/components/search/searchResults.js
  src/components/simple/linkList.js
Labels: size/xs

#168 ADAPT-3714: set focus to the number of results when the "View Results…
  src/components/page-types/searchPage.js
  src/components/search/searchResults.js
Labels: size/xs

#172 ADAPT-3713: Autocomplete combobox changes
  src/components/search/searchAutocomplete.js
  src/components/search/searchField.js
Labels: size/xs

#175 ADAPT-3736 | @mattanglin | fix search pagination
  src/components/page-types/searchPage.js
Labels: size/xs

#176 ADAPT-3741: Make card content background color fill the border
  src/components/content-types/story/storyCardView.js
Labels: size/xs

#178 ADAPT-3742: Adjust utility nav so it doesn't wrap to 2nd line for 360-374px devices
  src/components/composite/poster.js
  src/components/identity/masthead.js
  src/tailwind/plugins/theme/screens.js
  tailwind.config.js
Labels: size/xs

#177 ADAPT-000: Misc fixes
  src/components/cards/perkCard.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkCardView.js
  src/components/content-types/story/storyCardView.js
  src/components/layout/modal.js
  src/components/page-types/searchPage.js
  src/components/search/searchFieldModal.js
Labels: size/xs

#173 ADAPT-3265 | @mattanglin | trip filter page
  src/components/cards/TripCard/TripCard.jsx
  src/components/components.js
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/hooks/useTripFilterDatasources.js
  src/hooks/useTripFilters.js
  src/hooks/useTrips.js
  src/utilities/filterTrips.js
Labels: size/l

#180 ADAPT-3310: Add image width and height tags
  src/components/cards/basicCard.js
  src/components/composite/poster.js
  src/components/content-types/event/event.js
  src/components/content-types/story/storyCardView.js
  src/components/identity/logo.js
  src/components/media/cardImage.js
  src/components/media/circularImage.js
  src/components/media/fullWidthImage.js
  src/components/media/simpleImage.js
  src/utilities/addBgImage.js
  src/utilities/getImageSize.js
  src/utilities/getImageWidth.js
Labels: size/s

#179 ADAPT-3274 | @mattanglin | trip filters sidebar
  gatsby-browser.js
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/components/composite/TripFilterList/TripFilterList.styles.js
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/simple/FilterCheckbox/FilterCheckbox.jsx
  src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
  src/hooks/useTripFilters.js
  src/utilities/filterTrips.js
Labels: size/m

#184 ADAPT-3702: Add intro to ankle region
  src/components/content-types/story/storyPageView.js
  src/components/page-types/basicPage.js
  src/components/page-types/darkPage.js
  src/components/partials/ankle.js
  src/components/partials/ankle/ankle.jsx
  src/components/partials/ankle/ankleStyles.js
  tailwind.config.js
Labels: size/m

#182 ADAPT-3286 | @mattanglin | trip filter chips
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/simple/Chip/Chip.jsx
  src/components/simple/Chip/Chip.styles.js
  src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
  src/hooks/useTripFilters.js
Labels: size/s

#183 ADAPT-3280 | @mattanglin | trip filter content bloks
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
Labels: size/xs

#181 ADAPT-3287 | @mattanglin | trip filter pagination
  package-lock.json
  package.json
  src/components/composite/Pagination/Pagination.jsx
  src/components/composite/Pagination/Pagination.styles.js
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/hooks/usePaginationLinks.js
  src/hooks/useTripFilters.js
  src/types/TripType.js
  src/utilities/dom.js
  src/utilities/filterTrips.js
Labels: size/m

#186 ADAPT-3763 | @mattanglin | update trip filtering behaviors
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/hooks/useTripFilters.js
  src/utilities/filterTrips.js
Labels: size/m

#187 ADAPT-3268 | @mattanglin | primary filter trip filter page
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/hooks/useTripFilters.js
  src/utilities/filterTrips.js
Labels: size/xs

#188 ADAPT-3768 | @mattanglin | multi-option region trips
  src/utilities/filterTrips.js
Labels: size/xs

#185 ADAPT-3266: Global Header (Desktop and Mobile)
  gatsby-config.js
  src/components/components.js
  src/components/identity/global-header/GlobalHeader.jsx
  src/components/identity/global-header/GlobalHeaderStyles.js
  src/components/identity/masthead.js
  src/components/navigation/UtilityNav.jsx
  src/components/search/openSearchModalButton.js
  src/components/storyblok/globalHeader.jsx
  src/components/storyblok/globalHeaderPicker.jsx
  src/components/storyblok/utilityNav.jsx
  src/types/NavItemType.js
  src/types/storyblok/SBLinkType.js
  src/utilities/createStory.js
Labels: size/m

#189 ADAPT-3776: Updating Redirects
  static/_redirects
Labels: size/xs

#191 ADAPT-3256 | @mattanglin | trip page hero section
  src/components/components.js
  src/components/composite/HeroImage/HeroImage.jsx
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/page-types/TripPage.jsx
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPage.styles.js
  src/components/page-types/TripPage/TripPageHeroSection.jsx
  src/components/page-types/TripPage/TripPageHeroSection.styles.js
  src/components/storyblok/hero.jsx
  src/components/storyblok/tripCard.jsx
  src/types/TripType.js
  src/types/storyblok/SBAssetType.js
Labels: size/s

#194 Merge main into dev
  src/components/cards/basicCard.js
  src/components/cards/perkCard.js
  src/components/composite/poster.js
  src/components/content-types/event/event.js
  src/components/content-types/story/storyCardView.js
  src/components/identity/logo.js
  src/components/layout/modal.js
  src/components/media/cardImage.js
  src/components/media/circularImage.js
  src/components/media/fullWidthImage.js
  src/components/media/simpleImage.js
  src/components/page-types/searchPage.js
  src/components/search/searchFieldModal.js
  src/tailwind/plugins/theme/screens.js
  src/utilities/addBgImage.js
  src/utilities/getImageSize.js
  src/utilities/getImageWidth.js
  tailwind.config.js
Labels: size/s

#195 ADAPT-3257 | @mattanglin | trip page overview section
  package-lock.json
  package.json
  src/components/composite/CopyButton/CopyButton.jsx
  src/components/composite/CopyButton/CopyButton.styles.js
  src/components/composite/HeroImage/HeroImage.jsx
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.styles.js
  src/components/page-types/TripPage/TripPageSectionWrapper.jsx
  src/components/page-types/TripPage/TripPageSectionWrapper.styles.js
  src/types/TripType.js
  src/types/storyblok/SBBlokType.js
  src/types/storyblok/SBRichTextType.js
  src/utilities/dates.js
  src/utilities/slugify.js
Labels: size/m

#169 ADAPT-2770 | @mattanglin | Adds basic auth to the user-guide
  netlify.toml
Labels: size/xs

#196 ADAPT-3258 | @mattanglin | trip page faculty section
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageFacultySection.jsx
  src/components/page-types/TripPage/TripPageFacultySection.styles.js
  src/components/page-types/TripPage/TripPageOverviewSection.styles.js
Labels: size/xs

#197 ADAPT-3297 | @mattanglin | trip page itinerary section
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageItinerarySection.jsx
  src/components/page-types/TripPage/TripPageItinerarySection.styles.js
  src/components/page-types/TripPage/TripPageSectionWrapper.styles.js
Labels: size/xs

#199 ADAPT-3283: Add ankle to trip filter and trip detail pages
  src/components/navigation/SAAMainNav/SAAMainNav.styles.js
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripPage/TripPage.jsx
Labels: size/xs

#171 ADAPT-000: Launch Prep.
  gatsby-config.js
  netlify.toml
  package-lock.json
  package.json
  plugins/netlify-plugin-wildcard-404-redirect/index.js
  plugins/netlify-plugin-wildcard-404-redirect/manifest.yml
  src/components/partials/htmlHead.js
  static/_redirects
Labels: size/l

#201 ADAPT-2943: Google Search Console verification
  static/google83a00cb6501cf923.html
Labels: size/xs
