Repository SU-SWS/saa_alumni, pull requests merged in 2021-11, with the labels that each got.

#229 ADAPT-3990: Trip Page changes and options to hide sections
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/types/TripType.js
Labels: size/s, task

#231 ADAPT-3958: Add Pricing section
  src/components/cards/TripCard/TripCard.styles.js
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPagePricingSection.jsx
  src/components/page-types/TripPage/TripPageSectionNav.jsx
  src/components/page-types/TripPage/TripPageSectionNav.styles.js
  src/types/TripType.js
Labels: size/s, feature

#234 ADAPT-3999: Add filter facet count to Trip Filter page
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/components/simple/FilterCheckbox/FilterCheckbox.jsx
  src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
Labels: size/xs, feature

#236 ADAPT-4029 | @mattanglin | missing filter facets in mobile
  src/utilities/filterTrips.js
Labels: size/xs, fix

#237 ADAPT-4018, ADAPT-4028: Related trips background color change; Basic Cards tweak
  src/components/cards/basicCardContent.js
  src/components/page-types/TripPage/TripPageRelatedTripsSection.jsx
  src/components/page-types/TripPage/TripPageRelatedTripsSection.styles.js
Labels: size/xs, feature

#235 ADAPT-3275: Mobile filters
  src/components/cards/TripCard/TripCard.styles.js
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/components/composite/TripFilterList/TripFilterList.styles.js
  src/components/identity/global-header/GlobalHeader.jsx
  src/components/identity/global-header/GlobalHeader.styles.js
  src/components/identity/masthead.js
  src/components/layout/Modal/Modal.jsx
  src/components/layout/Modal/Modal.styles.js
  src/components/layout/modal.js
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterModal.styles.js
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/search/openSearchModalButton.js
  src/components/search/searchModal.js
  src/components/simple/Chip/Chip.styles.js
  src/components/simple/Date/Date.styles.js
  src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
  src/hooks/useMediaQuery.js
  src/hooks/useWindowSize.js
  src/tailwind/plugins/theme/colors.js
  src/utilities/dataSource.js
Labels: size/l, feature

#240 ADAPT-4026 | @mattanglin | staging site
  .github/workflows/merge-to-stage.yml
  netlify.toml
  plugins/netlify-plugin-contextual-auth/index.js
  plugins/netlify-plugin-contextual-auth/manifest.yml
Labels: size/xs, task

#233 ADAPT-3983: Remove 403/404 paths as they are now redirects.
  gatsby-node.js
  package-lock.json
Labels: size/xs

#242 ADAPT-3983: Remove 403/404 paths as they are now redirects. (#233)
  gatsby-node.js
  package-lock.json
Labels: patch

#241 ADAPT-4031: Adding t/s search page
  gatsby-browser.js
  package-lock.json
  src/components/identity/global-header/GlobalHeader.jsx
  src/components/identity/masthead.js
  src/components/search/searchModal.js
  src/components/storyblok/globalHeader.jsx
Labels: size/xs

#238 ADAPT-3267, ADAPT-4053: Print styles + modal and misc tweaks + block alignment for WYSIWYG
  src/components/cards/basicCardHorizontal.js
  src/components/cards/iconCard.js
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/composite/itineraryItem.js
  src/components/composite/poster.js
  src/components/cta/SAALinkButton.styles.js
  src/components/cta/ctaLink.js
  src/components/identity/global-header/GlobalHeader.styles.js
  src/components/identity/localFooter.js
  src/components/layout/Modal/Modal.jsx
  src/components/layout/Modal/Modal.styles.js
  src/components/layout/widthBox.js
  src/components/media/circularImage.js
  src/components/media/embedVideo.js
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterModal.styles.js
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPage.styles.js
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageExtensionSection.styles.js
  src/components/page-types/TripPage/TripPageItinerarySection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/TripPage/TripPageRelatedTripsSection.styles.js
  src/components/page-types/TripPage/TripPageSectionNav.styles.js
  src/components/page-types/TripPage/TripPageSectionWrapper.styles.js
  src/components/partials/ankle/ankle.jsx
  src/components/partials/ankle/ankle.styles.js
  src/components/partials/footer.js
  src/components/partials/header.js
  src/components/simple/wysiwyg.js
  src/tailwind/plugins/components/shadow/text-shadow.js
  src/tailwind/plugins/theme/screens.js
  src/utilities/dataSource.js
  src/utilities/filterTrips.js
  src/utilities/richTextRenderer.js
Labels: size/m, feature

#243 ADAPT-4020, ADAPT-4021: Hide all trip content except hero and display alert after trip has started
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPage.styles.js
  src/utilities/dates.js
Labels: size/s, feature

#245 Release/ADAPT-3292 Preset and component updates
  .github/workflows/merge-to-stage.yml
  gatsby-browser.js
  gatsby-config.js
  netlify.toml
  package-lock.json
  plugins/netlify-plugin-contextual-auth/index.js
  plugins/netlify-plugin-contextual-auth/manifest.yml
  src/components/cards/basicCardHorizontal.js
  src/components/cards/iconCard.js
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/composite/itineraryItem.js
  src/components/composite/poster.js
  src/components/cta/SAALinkButton.styles.js
  src/components/cta/ctaLink.js
  src/components/identity/global-header/GlobalHeader.jsx
  src/components/identity/global-header/GlobalHeader.styles.js
  src/components/identity/localFooter.js
  src/components/identity/masthead.js
  src/components/layout/Modal/Modal.jsx
  src/components/layout/Modal/Modal.styles.js
  src/components/layout/widthBox.js
  src/components/media/circularImage.js
  src/components/media/embedVideo.js
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterModal.styles.js
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPage.styles.js
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageExtensionSection.styles.js
  src/components/page-types/TripPage/TripPageItinerarySection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/TripPage/TripPageRelatedTripsSection.jsx
  src/components/page-types/TripPage/TripPageRelatedTripsSection.styles.js
  src/components/page-types/TripPage/TripPageSectionNav.styles.js
  src/components/page-types/TripPage/TripPageSectionWrapper.styles.js
  src/components/partials/ankle/ankle.jsx
  src/components/partials/ankle/ankle.styles.js
  src/components/partials/footer.js
  src/components/partials/header.js
  src/components/search/searchModal.js
  src/components/simple/wysiwyg.js
  src/components/storyblok/globalHeader.jsx
  src/tailwind/plugins/components/shadow/text-shadow.js
  src/tailwind/plugins/theme/screens.js
  src/utilities/dataSource.js
  src/utilities/dates.js
  src/utilities/filterTrips.js
  src/utilities/richTextRenderer.js
Labels: size/l, patch

#244 ADAPT-3386: Use the email field for email link url
  src/utilities/sbLink.js
Labels: size/xs

#247 nojira | @mattanglin | these alerts are just wrong
  src/components/composite/alert.js
Labels: size/xs, fix

#246 ADAPT-3273: Travel Study metatags and SEO; Overview and trip extension date display tweak
  src/components/composite/alert.js
  src/components/composite/globalAlert.js
  src/components/composite/itineraryItem.js
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/partials/seo.js
  src/components/simple/FilterCheckbox/FilterCheckbox.jsx
  src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
  src/hooks/useSubsite.js
Labels: size/s, feature

#228 ADAPT-3946: Decouple Stanford Logo, Global Footer, Heading from Decanter-React
  src/components/cards/GradientCard/GradientCard.jsx
  src/components/cards/TripCard/TripCard.jsx
  src/components/cards/basicCardContent.js
  src/components/cards/iconCard.js
  src/components/components.js
  src/components/composite/CopyButton/CopyButton.jsx
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/components/composite/itineraryItem.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkPageView.js
  src/components/content-types/story/storyPageView.js
  src/components/identity/GlobalFooter/GlobalFooter.jsx
  src/components/identity/GlobalFooter/GlobalFooter.styles.js
  src/components/identity/StanfordLogo/StanfordLogo.jsx
  src/components/identity/StanfordLogo/StanfordLogo.styles.js
  src/components/layout/section.js
  src/components/media/embedVideo.js
  src/components/navigation/linkGroup.js
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageHeroSection.jsx
  src/components/page-types/TripPage/TripPageHeroSection.styles.js
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/TripPage/TripPageRelatedTripsSection.jsx
  src/components/page-types/TripPage/TripPageSectionHeader.jsx
  src/components/page-types/TripPage/TripPageSectionWrapper.jsx
  src/components/page-types/basicPage.js
  src/components/page-types/darkPage.js
  src/components/page-types/searchPage.js
  src/components/partials/ankle/ankle.jsx
  src/components/partials/footer.js
  src/components/search/searchFacet.js
  src/components/search/searchModal.js
  src/components/search/searchNoResults.js
  src/components/search/searchResults.js
  src/components/search/searchSuggestions.js
  src/components/simple/Heading.jsx
  src/components/simple/heading.js
  src/components/simple/linkList.js
  src/components/storyblok/heading.jsx
  src/types/HeadingLevelType.js
  src/types/TypographyType.js
  src/utilities/dataSource.js
  src/utilities/richTextRenderer.js
Labels: size/l, task

#249 ADAPT-4088: Change Accommodations (hotel) field to rich text
  src/components/composite/itineraryItem.js
Labels: size/s, feature

#251 ADAPT-4090: Remove delay of masthead/global header rendering
  src/components/identity/global-header/GlobalHeader.jsx
  src/components/identity/masthead.js
  src/hooks/useDisplay.js
Labels: size/xs, task

#248 Release/Travel Study minor updates
  src/components/composite/alert.js
  src/components/composite/globalAlert.js
  src/components/composite/itineraryItem.js
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/partials/seo.js
  src/components/simple/FilterCheckbox/FilterCheckbox.jsx
  src/components/simple/FilterCheckbox/FilterCheckbox.styles.js
  src/hooks/useSubsite.js
  src/utilities/sbLink.js
Labels: size/s, patch

#253 Release: Masthead rendering improvement, itinerary schema change, decouple Decanter React part 1
  src/components/cards/GradientCard/GradientCard.jsx
  src/components/cards/TripCard/TripCard.jsx
  src/components/cards/basicCardContent.js
  src/components/cards/iconCard.js
  src/components/components.js
  src/components/composite/CopyButton/CopyButton.jsx
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/components/composite/itineraryItem.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkPageView.js
  src/components/content-types/story/storyPageView.js
  src/components/identity/GlobalFooter/GlobalFooter.jsx
  src/components/identity/GlobalFooter/GlobalFooter.styles.js
  src/components/identity/StanfordLogo/StanfordLogo.jsx
  src/components/identity/StanfordLogo/StanfordLogo.styles.js
  src/components/identity/global-header/GlobalHeader.jsx
  src/components/identity/masthead.js
  src/components/layout/section.js
  src/components/media/embedVideo.js
  src/components/navigation/linkGroup.js
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageHeroSection.jsx
  src/components/page-types/TripPage/TripPageHeroSection.styles.js
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/TripPage/TripPageRelatedTripsSection.jsx
  src/components/page-types/TripPage/TripPageSectionHeader.jsx
  src/components/page-types/TripPage/TripPageSectionWrapper.jsx
  src/components/page-types/basicPage.js
  src/components/page-types/darkPage.js
  src/components/page-types/searchPage.js
  src/components/partials/ankle/ankle.jsx
  src/components/partials/footer.js
  src/components/search/searchFacet.js
  src/components/search/searchModal.js
  src/components/search/searchNoResults.js
  src/components/search/searchResults.js
  src/components/search/searchSuggestions.js
  src/components/simple/Heading.jsx
  src/components/simple/heading.js
  src/components/simple/linkList.js
  src/components/storyblok/heading.jsx
  src/hooks/useDisplay.js
  src/types/HeadingLevelType.js
  src/types/TypographyType.js
  src/utilities/dataSource.js
  src/utilities/richTextRenderer.js
Labels: size/l
