Repository SU-SWS/saa_alumni, pull requests merged in 2021-04, with the labels that each got.

#10 ADAPT-2183: Tailwind JIT.
  gatsby-config.js
  gatsby-ssr.js
  package-lock.json
  package.json
  postcss.config.js
  src/components/partials/htmlHead.js
  src/styles/global.css
  tailwind.config.js
Labels: size/l

#8 ADAPT-2183 ADAPT-2065 ADAPT-2180 ADAPT-2134: Use Tailwind v2.1, global & local footer, CTA Link, Social Icon
  .gitignore
  example.env
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  gatsby-ssr.js
  package-lock.json
  package.json
  postcss.config.js
  src/components/components.js
  src/components/embed/embed.js
  src/components/identity/localFooter.js
  src/components/identity/localFooterPicker.js
  src/components/navigation/linkGroup.js
  src/components/navigation/navItem.js
  src/components/page-types/interiorPage.js
  src/components/page.js
  src/components/partials/footer.js
  src/components/partials/header.js
  src/components/partials/htmlHead.js
  src/components/partials/layout.js
  src/components/partials/seo.js
  src/components/simple/ctaLink.js
  src/components/simple/socialIconLink.js
  src/components/simple/wysiwyg.js
  src/contexts/GlobalContext.js
  src/hooks/useEscape.js
  src/hooks/useOnClickOutside.js
  src/hooks/useSiteMetadata.js
  src/html.js
  src/pages/editor.js
  src/styles/global.css
  src/tailwind/plugins/components/underline/custom-underline.js
  src/tailwind/plugins/theme/colors.js
  src/utilities/createBloks.js
  src/utilities/createStories.js
  src/utilities/dataSource.js
  src/utilities/getImageWidth.js
  src/utilities/getNumBloks.js
  src/utilities/richTextRenderer.js
  src/utilities/sbLink.js
  src/utilities/transformImage.js
  static/images/saa-logo-white.svg
  tailwind.config.js
Labels: size/xl

#12 ADAPT-2223: Rewrite editor.js page so it doesn't cause Gatsby V3 build warnings.
  gatsby-config.js
  package-lock.json
  src/pages/editor.js
Labels: size/xl

#15 Update editor.js
  src/pages/editor.js
Labels: size/xs

#17 ADAPT-000: Add tailwind-children & tailwind-interaction-variant plugins
  package-lock.json
  package.json
  src/components/partials/footer.js
  src/utilities/dataSource.js
  tailwind.config.js
Labels: size/xl

#18 ADAPT-2223: Storyblok Editor V1 Updates
  package-lock.json
  src/pages/editor.js
  src/utilities/createStories.js
Labels: size/m

#11 ADAPT-2114 ADAPT-2184: Hero, CTA Button, CTA Group components
  package-lock.json
  package.json
  src/components/components.js
  src/components/composite/hero.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaGroup.js
  src/components/cta/ctaLink.js
  src/components/identity/localFooter.js
  src/components/media/fullWidthImage.js
  src/components/page.js
  src/tailwind/plugins/base/base.js
  src/tailwind/plugins/components/gradient-border/gradient-border.js
  src/tailwind/plugins/components/shadow/text-shadow.js
  src/tailwind/plugins/components/underline/custom-underline.js
  src/tailwind/plugins/components/underline/link-underline.js
  src/tailwind/plugins/theme/colors.js
  src/utilities/createBloks.js
  src/utilities/dataSource.js
  src/utilities/transformImage.js
  tailwind.config.js
Labels: size/l

#20 ADAPT-2327: Added possibility to create Redirects
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/components.js
  src/components/redirect/Redirect.js
Labels: size/m

#22 ADAPT-2116: Suggested Edits.
  package-lock.json
  package.json
  src/components/cards/basicCard.js
  src/components/component_not_found.js
  src/components/composite/hero.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaGroup.js
  src/components/cta/ctaLink.js
  src/components/embed/embed.js
  src/components/identity/localFooter.js
  src/components/identity/localFooterPicker.js
  src/components/layout/grid.js
  src/components/navigation/linkGroup.js
  src/components/navigation/navItem.js
  src/components/page-types/interiorPage.js
  src/components/page.js
  src/components/partials/footer.js
  src/components/partials/header.js
  src/components/partials/htmlHead.js
  src/components/partials/layout.js
  src/components/partials/seo.js
  src/components/redirect/Redirect.js
  src/components/simple/wysiwyg.js
Labels: size/xl

#21 ADAPT-2116 ADAPT-2387 Section, Grid components
  package-lock.json
  package.json
  src/components/cards/basicCard.js
  src/components/component_not_found.js
  src/components/components.js
  src/components/composite/hero.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaGroup.js
  src/components/cta/ctaLink.js
  src/components/embed/embed.js
  src/components/identity/localFooter.js
  src/components/identity/localFooterPicker.js
  src/components/layout/grid.js
  src/components/layout/section.js
  src/components/layout/widthBox.js
  src/components/media/cardImage.js
  src/components/media/fullWidthImage.js
  src/components/navigation/linkGroup.js
  src/components/navigation/navItem.js
  src/components/page-types/interiorPage.js
  src/components/page.js
  src/components/partials/footer.js
  src/components/partials/header.js
  src/components/partials/htmlHead.js
  src/components/partials/layout.js
  src/components/partials/seo.js
  src/components/redirect/Redirect.js
  src/components/simple/wysiwyg.js
  src/tailwind/plugins/components/gradient-border/gradient-border.js
  src/tailwind/plugins/theme/colors.js
  src/tailwind/plugins/utilities/gradient-border/gradient-border.js
  src/utilities/dataSource.js
  src/utilities/richTextRenderer.js
  src/utilities/transformImage.js
  tailwind.config.js
Labels: size/xl
