Repository SU-SWS/saa_alumni, pull requests merged in 2021-12, with the labels that each got.

#255 ADAPT-4109: Trip Filter Page a11y fixes
  src/components/accessibility/Skiplink.jsx
  src/components/composite/Pagination/Pagination.jsx
  src/components/composite/TripFilterList/TripFilterList.jsx
  src/components/page-types/TripFilterPage/TripFilterModal.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.jsx
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/partials/basicContentLeftSidebar.js
  src/components/simple/FilterCheckbox/FilterCheckbox.jsx
Labels: size/s, task

#256 ADAPT-3950: Updated Gatsby to v4, along with dependencies.
  gatsby-config.js
  package-lock.json
  package.json
  src/utilities/config.js
Labels: size/xl, patch

#258 ADAPT-4133: Trip Page a11y fixes
  src/components/cards/iconCard.js
  src/utilities/richTextRenderer.js
Labels: size/xs, task

#257 ADAPT-4093: Add anchore to sbLink component
  src/utilities/sbLink.js
Labels: size/xs

#261 ADAPT-000: GraphQL inference for field_hideFromFilter_boolean
  gatsby-node.js
Labels: size/xs, task

#263 Hotfix: GQL Inference for field_hideFromFilter_boolean
  gatsby-node.js
Labels: size/xs, fix

#265 ADAPT-4208: Add 1 day to filter trip duration since we're doing inclusive # of days
  src/utilities/filterTrips.js
Labels: size/xs, fix
