Repository SU-SWS/saa_alumni, pull requests merged in 2021-05, with the labels that each got.

#23 ADAPT-2440 ADAPT-2447 ADAPT-2486: A11y fixes for hero/local footer; allow heading level selection for Section and Hero; addBgImage utility
  src/components/cards/basicCard.js
  src/components/composite/hero.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaLink.js
  src/components/identity/localFooter.js
  src/components/layout/section.js
  src/components/media/fullWidthImage.js
  src/components/navigation/linkGroup.js
  src/components/partials/header.js
  src/utilities/addBgImage.js
  src/utilities/dataSource.js
Labels: size/s

#24 ADAPT-2067 ADAPT-2277 ADAPT-2271 Perks & Benefits content type and card view
  gatsby-config.js
  package-lock.json
  src/components/cards/perkCard.js
  src/components/components.js
  src/components/composite/hero.js
  src/components/content-types/perk/perk.js
  src/components/content-types/perk/perkCardView.js
  src/components/content-types/perk/perkPageView.js
  src/components/identity/localFooter.js
  src/components/layout/grid.js
  src/components/simple/tabLabel.js
  src/tailwind/plugins/components/link/stretched-link.js
  src/tailwind/plugins/utilities/typography/writing-mode.js
  tailwind.config.js
Labels: size/xl

#28 ADAPT-2561: Perk Tweaks and use Decanter React v1.0.0
  package-lock.json
  package.json
  src/components/cards/perkCard.js
  src/components/content-types/perk/perkCardView.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaLink.js
  src/components/identity/localFooter.js
  src/components/simple/tabLabel.js
  src/tailwind/plugins/components/underline/custom-underline.js
Labels: size/s

#30 ADAPT-000: transformImage fix
  src/utilities/transformImage.js
Labels: size/xs

#32 ADAPT-2282 Create Poster Component
  src/components/cards/basicCard.js
  src/components/components.js
  src/components/composite/poster.js
  src/components/media/circularImage.js
Labels: size/s
