Repository SU-SWS/saa_alumni, pull requests merged in 2021-06, with the labels that each got.

#33 ADAPT-2658 Dark poster variants
  src/components/cards/basicCard.js
  src/components/composite/poster.js
  src/components/content-types/perk/perkCardView.js
  src/components/identity/localFooter.js
  src/components/media/cardImage.js
  src/components/media/circularImage.js
  src/tailwind/plugins/theme/colors.js
  src/utilities/dataSource.js
Labels: size/s

#34 ADAPT-2568 Add alignment boolean to Sections component
  src/components/layout/section.js
Labels: size/xs

#27 ADAPT-2279 ADAPT-2534 Events content type and event cards
  gatsby-config.js
  package-lock.json
  package.json
  src/components/cards/basicCard.js
  src/components/cards/eventCard.js
  src/components/components.js
  src/components/content-types/event/event.js
  src/components/simple/dateBlock.js
  src/components/simple/tabLabel.js
  src/tailwind/plugins/components/underline/custom-underline.js
Labels: size/m

#35 ADAPT-2437: Create embedCard
  gatsby-node.js
  package-lock.json
  package.json
  src/components/cards/embedCard.js
  src/components/components.js
Labels: size/m

#31 ADAPT-2072 ADAPT-2113 ADAPT-2069 ADAPT-2765: Main Navigation, Masthead, Basic Page, Hero config
  gatsby-config.js
  package-lock.json
  package.json
  src/components/components.js
  src/components/composite/hero.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaLink.js
  src/components/identity/localFooter.js
  src/components/identity/logo.js
  src/components/identity/masthead.js
  src/components/identity/mastheadPicker.js
  src/components/layout/section.js
  src/components/layout/widthBox.js
  src/components/navigation/mainMenuGroup.js
  src/components/navigation/mainNav.js
  src/components/navigation/mainNavItem.js
  src/components/navigation/navItem.js
  src/components/page-types/basicPage.js
  src/components/page-types/landingPage.js
  src/components/partials/basicContentLeftSidebar.js
  src/components/partials/basicContentNoSidebar.js
  src/components/partials/header.js
  src/components/partials/layout.js
  src/components/search/searchBar.js
  src/images/.keep
  src/images/saa-logo-white.svg
  src/tailwind/plugins/base/base.js
  src/tailwind/plugins/components/backface-visibility/backface-visibility.js
  src/tailwind/plugins/theme/colors.js
  src/utilities/createBloks.js
  src/utilities/richTextRenderer.js
  src/utilities/sbLink.js
  src/utilities/transformImage.js
  tailwind.config.js
Labels: size/xl

#39 ADAPT-2706 ADAPT-2113: Masthead Styles
  src/components/cards/basicCard.js
  src/components/identity/masthead.js
  src/components/navigation/mainMenuGroup.js
  src/components/navigation/mainNav.js
  src/components/navigation/mainNavItem.js
  src/components/partials/basicContentNoSidebar.js
  src/components/search/openSearchModalButton.js
  src/components/search/searchBar.js
  src/tailwind/plugins/theme/screens.js
  src/utilities/.gitkeep
  tailwind.config.js
Labels: size/s

#43 ADAPT-2778: Change Basic Card body text field to rich text
  src/components/cards/basicCard.js
Labels: size/xs

#37 ADAPT-2066: Global and Local Alerts
  gatsby-config.js
  package-lock.json
  src/components/cards/basicCard.js
  src/components/components.js
  src/components/composite/alert.js
  src/components/composite/globalAlert.js
  src/components/composite/hero.js
  src/components/cta/alertCtaLink.js
  src/components/layout/grid.js
  src/components/partials/header.js
  src/styles/alert.css
Labels: size/s

#45 ADAPT-000: Add backface-visibility:hidden to perk card gradient overlay
  src/components/content-types/perk/perkCardView.js
Labels: size/xs

#40 ADAPT-2675, ADAPT-2675, ADAPT-2676: Indexing for Youtube, Soundcloud, and iTunes content.
  lambda/config/indexMedia.config.js
  lambda/indexMedia.js
  package-lock.json
  package.json
Labels: size/xl

#50 ADAPT-000: GraphQL Build errors (#39)
  gatsby-config.js
  gatsby-node.js
Labels: size/xs

#49 ADAPT-2285: WYSIWYG
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/cards/basicCard.js
  src/components/layout/section.js
  src/components/simple/wysiwyg.js
  src/styles/global.css
  src/tailwind/plugins/components/wysiwyg/heading-link.js
  src/utilities/dataSource.js
  src/utilities/richTextRenderer.js
  static/images/arrow-right.svg
  tailwind.config.js
Labels: size/s

#46 ADAPT-2735 Build Simple Image component
  src/components/components.js
  src/components/media/simpleImage.js
Labels: size/xs

#52 ADAPT-000 Add "version:" for gatsby-source-storyblok
  gatsby-config.js
Labels: size/xs

#51 ADAPT-2740 Update and test SEO
  src/components/partials/seo.js
Labels: size/xs
