Repository SU-SWS/saa_alumni, pull requests merged in 2021-07, with the labels that each got.

#53 ADAPT-2734 Add Rich Media Component
  package.json
  src/components/components.js
  src/components/media/embedVideo.js
  src/utilities/dataSource.js
Labels: size/xs

#57 ADAPT-2661 Add mobile button padding
  src/utilities/dataSource.js
Labels: size/xs

#59 ADAPT-2903: Accessibility fixes
  src/components/composite/hero.js
  src/components/composite/poster.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkCardView.js
  src/components/cta/ctaButton.js
  src/components/layout/section.js
  src/components/navigation/mainMenuGroup.js
  src/components/simple/tabLabel.js
Labels: size/xs

#64 As a utility.
  package-lock.json
  src/tailwind/plugins/base/tw-amendment.js
  src/tailwind/plugins/utilities/break-words.js
  tailwind.config.js
Labels: size/s

#58 ADAPT-2929: Misc fixups
  package-lock.json
  src/components/cards/basicCard.js
  src/components/media/circularImage.js
  src/components/partials/basicContentLeftSidebar.js
  src/tailwind/plugins/base/base.js
  src/tailwind/plugins/utilities/break-words.js
  src/utilities/dataSource.js
  tailwind.config.js
Labels: size/l

#60 ADAPT-2880: Search Modal open/close behavior
  package-lock.json
  package.json
  src/components/layout/modal.js
  src/components/search/openSearchModalButton.js
  src/components/search/searchFieldModal.js
  src/components/search/searchModal.js
  src/hooks/useFocusTrap.js
Labels: size/xl

#66 ADAPT-000: Updates netlify cli tool.
  package-lock.json
  package.json
Labels: size/xl

#38 Search Page: ADAPT-2667, ADAPT-2670, ADAPT-2671, ADAPT-2660
  .eslintrc
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/components/components.js
  src/components/layout/grid.js
  src/components/layout/modal.js
  src/components/page-types/searchPage.js
  src/components/search/openSearchModalButton.js
  src/components/search/searchFacet.js
  src/components/search/searchField.js
  src/components/search/searchFieldModal.js
  src/components/search/searchModal.js
  src/components/search/searchNoResults.js
  src/components/search/searchPager.js
  src/components/search/searchResults.js
  src/components/simple/heading.js
  src/components/simple/linkList.js
  src/hooks/useFocusTrap.js
  src/tailwind/plugins/components/checkbox/custom-checkbox.js
  static/images/checked-icon.svg
  tailwind.config.js
Labels: size/xl

#62 ADAPT-2932 Add spacing options and full viewport style
  src/components/media/simpleImage.js
  src/utilities/dataSource.js
Labels: size/xs

#70 ADAPT-2857 Remove interior and landing page-types
  src/components/components.js
  src/components/page-types/interiorPage.js
  src/components/page-types/landingPage.js
Labels: size/xs

#65 ADAPT-2921: Story Page, Story Card tweak, Section options
  package-lock.json
  src/components/cards/basicCard.js
  src/components/cards/storyCard.js
  src/components/content-types/event/event.js
  src/components/content-types/story/storyCardView.js
  src/components/content-types/story/storyPageView.js
  src/components/layout/section.js
  src/components/media/captionMedia.js
  src/components/simple/heroIcon.js
  src/components/simple/wysiwyg.js
  src/tailwind/plugins/theme/colors.js
Labels: size/l

#54 ADAPT-000: Update gatsby-config version ternary
  gatsby-config.js
Labels: size/xs

#69 ADAPT-2397: Mobile main nav
  package-lock.json
  package.json
  src/components/identity/masthead.js
  src/components/navigation/mainMenuGroup.js
  src/components/navigation/mainNav.js
  src/components/navigation/mainNavItem.js
  src/components/navigation/navItem.js
Labels: size/l

#67 ADAPT-2705 Create CtaCard
  src/components/cards/ctaCard.js
  src/components/components.js
  src/utilities/dataSource.js
Labels: size/xs

#73 ADAPT 2900, ADAPT-2738: Icon card and ankle region
  package-lock.json
  package.json
  src/components/cards/iconCard.js
  src/components/components.js
  src/components/content-types/event/event.js
  src/components/content-types/story/storyCardView.js
  src/components/content-types/story/storyPageView.js
  src/components/page-types/basicPage.js
  src/components/page-types/darkPage.js
  src/components/partials/ankle.js
  src/components/partials/basicContentLeftSidebar.js
  src/components/partials/htmlHead.js
  src/components/simple/wysiwyg.js
  src/styles/global.css
  src/utilities/dataSource.js
Labels: size/xl

#72 ADAPT-2671: Pager fixes
  .github/workflows/eslint.yml
  gatsby-browser.js
  package-lock.json
  package.json
  src/components/content-types/perk/perkPageView.js
  src/components/page-types/searchPage.js
  src/components/search/searchPager.js
  src/components/search/searchResults.js
  src/utilities/buildPager.js
Labels: size/s

#71 ADAPT-2851: Add canonical url to SEO
  gatsby-config.js
  gatsby-node.js
  src/components/partials/seo.js
  src/templates/storyblok-entry.js
Labels: size/xs

#79 ADAPT-2835: Soundcloud Indexing
  lambda/config/indexMedia.config.js
  lambda/indexMedia.js
  package-lock.json
  package.json
Labels: size/m

#76 ADAPT-2922: Add FontAwesome leading icon to CTA Link; icon refactor
  src/components/cards/ctaCard.js
  src/components/cards/iconCard.js
  src/components/composite/hero.js
  src/components/content-types/event/event.js
  src/components/content-types/perk/perkCardView.js
  src/components/content-types/story/storyCardView.js
  src/components/content-types/story/storyPageView.js
  src/components/cta/ctaButton.js
  src/components/cta/ctaGroup.js
  src/components/cta/ctaLink.js
  src/components/layout/section.js
  src/components/simple/faIcon.js
  src/components/simple/heroIcon.js
  src/utilities/dataSource.js
  src/utilities/sbLink.js
Labels: size/l

#77 ADAPT-2679: Keyword Search Banners
  gatsby-node.js
  src/components/page-types/searchPage.js
  src/components/search/searchKeywordBanner.js
Labels: size/xs

#78 ADAPT-2988: Remove HeadlessUI Popover component from main nav
  src/components/navigation/mainMenuGroup.js
Labels: size/s

#81 Update htmlHead.js
  src/components/partials/htmlHead.js
Labels: size/xs

#87 ADAPT-000: Block robot from indexing
  netlify.toml
Labels: size/xs

#88 google-verify-code
  google3bfc006a07428fd8.html
Labels: size/xs

#75 ADAPT-2948 Add asset url
  src/components/partials/htmlHead.js
  src/components/simple/linkList.js
  src/utilities/richTextRenderer.js
  src/utilities/sbLink.js
  src/utilities/transformImage.js
  static/_redirects
Labels: size/xs

#85 ADAPT-3011: Add above and below content to search results page
  src/components/page-types/searchPage.js
Labels: size/xs

#90 Delete _redirects
  static/_redirects
Labels: size/xs

#86 ADAPT-2669: Adjust spacings for search input
  src/components/page-types/searchPage.js
  src/components/search/searchField.js
  src/components/search/searchFieldModal.js
Labels: size/xs

#92 ADAPT-2673: Add Empty search message to the search page
  src/components/page-types/searchPage.js
Labels: size/xs

#94 ADAPT-3057 Update Embed component caption to use the CaptionMedia
  src/components/media/embedVideo.js
Labels: size/xs

#96 ADAPT-3006: Media search result adjustments
  src/components/page-types/searchPage.js
  src/components/search/searchFacet.js
  src/components/search/searchResults.js
Labels: size/s

#97 ADAPT-3060 Refactor SimpleImage component to use transformImage and captionMedia components
  src/components/layout/widthBox.js
  src/components/media/captionMedia.js
  src/components/media/simpleImage.js
  src/utilities/dataSource.js
Labels: size/xs

#93 ADAPT-3028: Sanitized IDs for WYSIWYG, posters, sections; update form elements to use new version of decanter; remove gatsby-plugin-anchor-links
  gatsby-config.js
  package-lock.json
  package.json
  src/components/composite/hero.js
  src/components/composite/poster.js
  src/components/layout/modal.js
  src/components/layout/section.js
  src/components/navigation/mainMenuGroup.js
  src/components/navigation/mainNav.js
  src/components/partials/layout.js
  src/components/search/openSearchModalButton.js
  src/components/search/searchFieldModal.js
  src/components/simple/wysiwyg.js
  tailwind.config.js
Labels: size/xl

#102 ADAPT-000: Put back in decanter form classnames
  src/components/search/searchFacet.js
Labels: size/xs

#101 ADAPT-3028: Remove isNetlify check in transform image
  src/utilities/transformImage.js
Labels: size/xs

#100 ADAPT-3028: Grid tweaks and options
  src/components/layout/grid.js
  src/components/layout/widthBox.js
  src/utilities/dataSource.js
Labels: size/xs

#103 ADAPT-2665: Flip direction of search icon.
  src/components/search/searchFieldModal.js
Labels: size/xs
