Repository SU-SWS/saa_alumni, pull requests merged in 2022-03, with the labels that each got.

#302 ADAPT-4430: Updated github action to use labels for automatic semantic versioning.
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: size/xs, patch

#306 ADAPT-4534: Fix bug with incorrect login provider URL.
  lambda/auth.js
Labels: size/xs

#307 Release: v0.2.7
  .github/release-drafter.yml
  .github/workflows/release.yml
  netlify.toml
  package-lock.json
  package.json
  src/components/components.js
  src/components/composite/accordion.js
  src/components/composite/accordionItem.js
Labels: size/l, patch

#303 ADAPT-4412 | @rebeccahongsf | Add and configure global variables
  src/components/embed/giveGabForm.js
  src/utilities/giveGabVars.js
Labels: size/s, feature

#292 ADAPT-4168: Masthead theming
  package-lock.json
  src/components/identity/GlobalHeader/GlobalHeader.styles.js
  src/components/identity/masthead.js
  src/components/navigation/MainNav/mainNav.styles.js
  src/components/navigation/UtilityNav.jsx
  src/components/navigation/accountLinks.js
Labels: size/xl

#301 ADAPT-4437 ADAPT-4520 | @rebeccahongsf | clone megaprofile api and refactor oauth gateway
  lambda/.gitkeep
  lambda/auth.js
  lambda/config/indexMedia.config.js
  netlify.toml
  package-lock.json
  package.json
  plugins/netlify-plugin-vault-variables/README.md
  plugins/netlify-plugin-vault-variables/index.js
  plugins/netlify-plugin-vault-variables/manifest.yml
  plugins/netlify-plugin-vault-variables/package.json
  plugins/netlify-plugin-vault-variables/script.js
  src/api/auth/callback.js
  src/api/auth/login.js
  src/api/auth/logout.js
  src/api/auth/profile.js
  src/api/auth/session.js
  src/contexts/AuthContext.js
  src/utilities/ApiExceptions.js
  src/utilities/ApiGatewayAuth.js
  src/utilities/MegaProfile.js
  src/utilities/authInstance.js
  static/_redirects
Labels: size/xl, feature, patch

#314 nojira | @rebeccahongsf | remove tsgg dev from readme
  README.md
Labels: size/xs

#311 ADAPT-4536: Added affiliations to user profile.
  lambda/.gitkeep
  lambda/auth.js
  lambda/config/indexMedia.config.js
  netlify.toml
  package-lock.json
  package.json
  plugins/netlify-plugin-vault-variables/README.md
  plugins/netlify-plugin-vault-variables/index.js
  plugins/netlify-plugin-vault-variables/manifest.yml
  plugins/netlify-plugin-vault-variables/package.json
  plugins/netlify-plugin-vault-variables/script.js
  src/api/auth/callback.js
  src/api/auth/login.js
  src/api/auth/logout.js
  src/api/auth/profile.js
  src/api/auth/session.js
  src/components/navigation/accountLinks.js
  src/contexts/AuthContext.js
  src/utilities/ApiExceptions.js
  src/utilities/ApiGatewayAuth.js
  src/utilities/MegaProfile.js
  src/utilities/authInstance.js
  static/_redirects
Labels: size/xl, patch

#315 nojira | @rebeccahongsf | update tsgg with dev branch
  .github/release-drafter.yml
  .github/workflows/release.yml
  src/components/composite/accordion.js
Labels: size/xs, task

#309 ADAPT-4519 | @rebeccahongsf | create form page-type component
  gatsby-config.js
  src/components/components.js
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/composite/tripFormInformation.js
  src/components/embed/giveGabForm.js
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/tripNotifyMe.js
  src/components/page-types/formPage/tripNotifyMe.styles.js
  src/tailwind/plugins/theme/colors.js
Labels: size/s, feature

#310 ADAPT-4438 | @rebeccahongsf | add additional mp data endpoints
  src/api/auth/profile.js
  src/components/navigation/accountLinks.js
  src/contexts/AuthContext.js
  src/utilities/MegaProfile.js
Labels: size/xs, feature

#319 ADAPT-4438| @rebeccahongsf | fix userProfile first and last name
  src/components/navigation/accountLinks.js
Labels: size/xs, feature
