Repository SU-SWS/saa_alumni, pull requests merged in 2022-05, with the labels that each got.

#333 ADAPT-4416 | @rebeccahongsf | implement ux form theme feedback
  src/components/page-types/formPage/tripCustomJourneys.js
  src/components/page-types/formPage/tripNotifyMe.js
Labels: size/xs, feature

#334 RELEASE: v0.2.8
  .github/workflows/pr-labeler.yml
  README.md
  netlify.toml
  package-lock.json
  package.json
  plugins/netlify-plugin-vault-variables/README.md
  plugins/netlify-plugin-vault-variables/index.js
  plugins/netlify-plugin-vault-variables/manifest.yml
  plugins/netlify-plugin-vault-variables/package.json
  plugins/netlify-plugin-vault-variables/script.js
  static/_redirects
Labels: patch

#336 ADAPT-4414: Form theming fixed
  src/components/embed/giveGabForm.js
  src/styles/forms.css
Labels: size/xs

#327 ADAPT-4815 | @rebeccahongsf | rework mp api endpoint to fullgg
  package-lock.json
  package.json
  src/api/auth/profile.js
  src/components/navigation/accountLinks.js
  src/contexts/AuthContext.js
  src/utilities/getGgProfile.js
  src/utilities/giveGabVars.js
Labels: size/l, feature, patch

#338 ADAPT-4679 | @rebeccahongsf | rework trip reference and remove duplicated information from gg component
  gatsby-config.js
  src/components/embed/giveGabForm.js
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/tripCustomJourneys.js
  src/components/page-types/formPage/tripNotifyMe.js
Labels: size/xs, feature

#337 ADAPT-4414 | @rebeccahongsf | add single column layout option to form theme
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/embed/giveGabForm.js
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/tripNotifyMe.js
  src/tailwind/plugins/theme/colors.js
Labels: size/xs, feature

#340 nojira | @rebeccahongsf | fixup incorrect obj ref
  src/utilities/giveGabVars.js
Labels: size/xs, fix

#342 Perks Package Updates
  README.md
  netlify.toml
  package-lock.json
  package.json
  postcss.config.js
  src/components/cards/promoCodeBanner.js
  src/styles/global.css
  src/utilities/richTextRenderer.js
  static/_redirects
  tailwind.config.js
Labels: patch

#346 Perks integration
  .github/workflows/pr-labeler.yml
  README.md
  gatsby-node.js
  gatsby-ssr.js
  netlify.toml
  package-lock.json
  package.json
  postcss.config.js
  src/api/auth/login.js
  src/api/auth/profile.js
  src/api/private-proxy.js
  src/components/cards/GradientCard/GradientCard.styles.js
  src/components/cards/TripCard/TripCard.styles.js
  src/components/cards/basicCardContent.js
  src/components/cards/ctaCard.js
  src/components/cards/iconCard.js
  src/components/cards/promoCodeBanner.js
  src/components/cards/protectedContentItem.js
  src/components/cards/saaStoryCard.js
  src/components/components.js
  src/components/composite/accordionItem.js
  src/components/composite/hero.js
  src/components/content-types/event/event.js
  src/components/cta/SAACtaLink.styles.js
  src/components/cta/SAALinkButton.styles.js
  src/components/cta/ctaGroup.js
  src/components/identity/GlobalHeader/GlobalHeader.styles.js
  src/components/identity/localFooter.js
  src/components/layout/Modal/Modal.styles.js
  src/components/layout/ProtectedContentWrapper.jsx
  src/components/layout/section.js
  src/components/navigation/MainNav/mainMenuGroup.styles.js
  src/components/navigation/MainNav/mainNav.styles.js
  src/components/navigation/MainNav/mainNavitem.styles.js
  src/components/navigation/accountLinks.js
  src/components/navigation/verticalNav.js
  src/components/navigation/verticalNavItem.js
  src/components/navigation/verticalNavWrapper.js
  src/components/page-types/TripFilterPage/TripFilterModal.styles.js
  src/components/page-types/TripFilterPage/TripFilterPage.styles.js
  src/components/page-types/TripPage/TripPageOverviewSection.styles.js
  src/components/page-types/TripPage/TripPageSectionNav.styles.js
  src/components/page-types/searchPage.js
  src/components/search/searchResults.js
  src/components/simple/Chip/Chip.styles.js
  src/components/simple/heroIcon.js
  src/components/storyblok/alert/alert.jsx
  src/contexts/AuthContext.js
  src/styles/global.css
  src/utilities/ApiGatewayAuth.js
  src/utilities/MegaProfile.js
  src/utilities/getGgProfile.js
  src/utilities/mockServer.js
  src/utilities/mocks/affiliations.js
  src/utilities/mocks/fullgg.js
  src/utilities/mocks/index.js
  src/utilities/richTextRenderer.js
  static/_redirects
  tailwind.config.js
Labels: patch

#339 ADAPT-4862: GG/Storyblok API Example Integration
  src/api/trips/gg.js
  src/api/trips/index.js
Labels: size/m, patch

#349 nojira | @rebeccahongsf | add trip post extension options
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#351 ADAPT-4416 | @rebeccahongsf | fixup one column layout theme
  src/components/page-types/formPage/formPage.js
Labels: feature

#348 ADAPT-4682 | @rebeccahongsf | create category and extension options api
  src/api/travel-study/gg.js
  src/api/travel-study/index.js
  src/api/travel-study/reg/post-extension.js
  src/api/travel-study/reg/pre-extension.js
  src/api/travel-study/reg/room-category.js
  src/api/travel-study/reg/trip-deposit.js
  src/components/embed/giveGabForm.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/utilities/formatDataCsv.js
  src/utilities/getAllTrips.js
  src/utilities/getTripFormStory.js
Labels: feature

#344 ADAPT-4963: Staff Forms POC
  src/api/travel-study/trips/index.js
  static/scripts/travel-study/gg-form.js
  static/test-notify-me.html
Labels: size/m

#352 ADAPT-4681 | @rebeccahongsf | update prefill data
  src/components/page-types/formPage/formPage.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registationFormOptions.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/tripTravelerCard.js
  src/components/page-types/registrationFormPage/tripTravelerListItem.js
  src/utilities/giveGabVars.js
Labels: feature
