Repository SU-SWS/saa_alumni, pull requests merged in 2022-07, with the labels that each got.

#379 ADAPT-5098 | Add background color option to protected content item
  src/components/cards/protectedContentItem.js
Labels: task

#380 Release/v.1.0.1
  src/components/cards/protectedContentItem.js
Labels: patch

#382 ADAPT-5088 | @rebeccahongsf | update internal vars
  src/api/travel-study/trips/index.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  static/gg-test/traveler-scenario/21-test.html
  static/scripts/travel-study/gg-form.css
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#383 ADAPT-5088 | @rebeccahongsf | add urlData to trip form
  static/scripts/travel-study/assets/arrow-down.svg
  static/scripts/travel-study/assets/calendar.svg
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#385 ADAPT-5034 | @rebeccahongsf | dev updates
  src/components/cards/protectedContentItem.js
Labels: feature

#387 ADAPT-5020 | @rebeccahongsf | oneliner font size fix
  static/scripts/travel-study/gg-form.css
Labels: feature

#388 ADAPT-5020 | @rebeccahongsf | back button font accessibility fix
  static/scripts/travel-study/gg-form.css
Labels: feature

#389 nojira | @rebeccahongsf | account for direct navigation to regForm
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#391 Release V1.0.2
  src/api/auth/login.js
  src/components/auth/AuthenticatedPage.js
  src/components/navigation/accountLinks.js
Labels: patch

#395 ADAPT-5012 | @rebeccahongsf | add small plus and minus icon, update icon style on traveler card
  src/components/page-types/registrationFormPage/tripTravelerCard.js
  src/components/simple/heroIcon.js
Labels: feature

#392 ADAPT-5006 | @rebeccahongsf | notify me r1 qa
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/tripCustomJourneys.js
  src/components/page-types/formPage/tripNotifyMe.js
  src/components/page-types/formPage/tripNotifyMe.styles.js
  src/tailwind/plugins/theme/colors.js
Labels: feature

#399 ADAPT-5112 | @rebeccahongsf | redirect from registration form
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#402 ADAPT-5112 | @rebeccahongsf | adjust redirect location and conditional
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#404 Release V1.0.3
  src/components/composite/Alert/globalAlert.js
Labels: patch

#396 ADAPT-5093 | @rebeccahongsf | adjust utm params and update tsgg branch
  src/components/auth/AuthenticatedPage.js
  src/components/cards/TripCard/TripCard.jsx
  src/components/navigation/accountLinks.js
  src/components/search/searchField.js
  src/components/search/searchResults.js
  src/utilities/sbLink.js
  src/utilities/utmParams.js
Labels: feature

#408 ADAPT-5139 | @rebeccahongsf | staff form fixup
  static/scripts/travel-study/assets/arrow-down.svg
  static/scripts/travel-study/gg-form.css
  static/scripts/travel-study/gg-form.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#410 ADAPT-5139 | @rebeccahongsf | staff form quick fix
  static/scripts/travel-study/gg-form.css
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#412 ADAPT-5139 | @rebeccahongsf | staff forms fixup r2
  static/scripts/travel-study/gg-form.css
Labels: feature

#413 nojira | @rebeccahongsf | dev updates
  src/api/auth/login.js
  src/components/composite/Alert/globalAlert.js
Labels: feature

#415 ADAPT-5094 | @rebeccahongsf | patch regForm storyblok authoring exp
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#416 ADAPT-5212 | @rebeccahongsf | Add trip dates for Notify Me forms
  src/components/page-types/formPage/formPage.js
Labels: feature

#417 nojira | @rebeccahongsf | adjust access denied text align and loading text
  src/components/layout/ProtectedContentWrapper.jsx
Labels: feature

#398 ADAPT-5108 | @rebeccahongsf | add givegab failure message
  gatsby-config.js
  src/components/components.js
  src/components/embed/dynaScript.js
  src/components/embed/giveGabErrorMessage.js
  src/components/embed/giveGabForm.js
  src/components/page-types/formPage/formPage.js
Labels: feature

#418 ADAPT-5215 | @rebeccahongsf | add getDateOnly func for internal forms
  static/scripts/travel-study/gg-trip-form.js
Labels: feature
