Repository SU-SWS/saa_alumni, pull requests merged in 2022-06, with the labels that each got.

#354 Support Mulesoft and Keycloak oauth providers for FullGG
  src/api/auth/profile.js
  src/components/composite/Alert/globalAlert.js
  src/components/navigation/accountLinks.js
  src/contexts/AuthContext.js
Labels: feature

#358 ADAPT-4979 | @rebeccahongsf | resolve su_reg type difference in api data
  static/gg-test/00-template.html
  static/gg-test/form-scenario/03-test.html
  static/gg-test/form-scenario/04-test.html
  static/gg-test/form-scenario/05-test.html
  static/gg-test/traveler-scenario/05-test.html
  static/gg-test/traveler-scenario/06-test.html
  static/gg-test/traveler-scenario/07-test.html
  static/gg-test/traveler-scenario/08-test.html
  static/gg-test/traveler-scenario/09-test.html
  static/gg-test/traveler-scenario/10-test.html
  static/gg-test/traveler-scenario/11-test.html
  static/gg-test/traveler-scenario/12-test.html
  static/gg-test/traveler-scenario/13-test.html
Labels: feature

#359 ADAPT-4979 | @rebeccahongsf | update test data su_reg related contact cap
  static/gg-test/00-template.html
  static/gg-test/form-scenario/03-test.html
  static/gg-test/form-scenario/04-test.html
  static/gg-test/form-scenario/05-test.html
  static/gg-test/traveler-scenario/08-test.html
  static/gg-test/traveler-scenario/09-test.html
  static/gg-test/traveler-scenario/10-test.html
Labels: feature

#357 Release V0.2.9
  src/components/media/cardImage.js
Labels: patch

#362 nojira | @rebeccahongsf | fix back to link for notify me and custom journeys form
  src/components/page-types/formPage/tripCustomJourneys.js
  src/components/page-types/formPage/tripNotifyMe.js
Labels: fix

#365 ADAPT-4678 | @rebeccahongsf | restructure interstitial theme
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/tripTravelerCard.js
  src/components/page-types/registrationFormPage/tripTravelerList.js
  src/components/page-types/registrationFormPage/tripTravelerListItem.js
  src/contexts/FormContext.js
Labels: feature

#367 ADAPT-5034 | @rebeccahongsf | perks sync, includes keycloak updates
  gatsby-config.js
  package-lock.json
  package.json
  src/api/auth/profile.js
  src/components/cards/GradientCard/GradientCard.styles.js
  src/components/cards/TripCard/TripCard.styles.js
  src/components/cards/ctaCard.js
  src/components/cards/iconCard.js
  src/components/cards/promoCodeBanner.js
  src/components/cards/saaStoryCard.js
  src/components/components.js
  src/components/composite/Alert/globalAlert.js
  src/components/composite/CopyButton/CopyButton.jsx
  src/components/composite/TripFilterList/TripFilterList.styles.js
  src/components/content-types/event/event.js
  src/components/cta/SAACtaLink.styles.js
  src/components/cta/SAALinkButton.styles.js
  src/components/identity/GlobalFooter/GlobalFooter.styles.js
  src/components/identity/GlobalHeader/GlobalHeader.styles.js
  src/components/identity/localFooter.js
  src/components/layout/ProtectedContentWrapper.jsx
  src/components/media/cardImage.js
  src/components/navigation/MainNav/mainMenuGroup.styles.js
  src/components/navigation/MainNav/mainNavitem.styles.js
  src/components/navigation/UtilityNav.jsx
  src/components/navigation/accountLinks.js
  src/components/navigation/navItem.js
  src/components/page-types/TripPage/TripPageSectionNav.styles.js
  src/components/simple/DismissButton/DismissButton.styles.js
  src/contexts/AuthContext.js
  src/styles/forms.css
  src/styles/localist.css
  src/tailwind/plugins/base/base.js
  src/tailwind/plugins/components/backface-visibility/backface-visibility.js
  src/tailwind/plugins/components/link/stretched-link.js
  src/tailwind/plugins/components/shadow/text-shadow.js
  src/tailwind/plugins/components/underline/custom-underline.js
  src/tailwind/plugins/theme/colors.js
  src/tailwind/plugins/utilities/break-words.js
  src/tailwind/plugins/utilities/typography/writing-mode.js
  src/utilities/MegaProfile.js
  src/utilities/dataSource.js
  src/utilities/getGgProfile.js
  tailwind.config.js
Labels: feature, patch

#368 nojia | @rebeccahongsf | quick fix for incorrect first name reference in user session data
  src/utilities/giveGabVars.js
Labels: fix

#371 ADAPT-4678 | @rebeccahongsf | add saa black dark to interstitial page and single col form theme
  src/components/page-types/formPage/formPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/tripTravelerCard.js
Labels: feature

#372 ADAPT-4979 | @rebeccahongsf | givegab reg test form updates
  static/gg-test/form-scenario/03-test.html
  static/gg-test/form-scenario/09-test.html
  static/gg-test/traveler-scenario/08-test.html
  static/gg-test/traveler-scenario/09-test.html
Labels: feature

#374 ADAPT-4979 | @rebeccahongsf | update prefix and user's prefill name
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/tripTravelerListItem.js
Labels: feature, patch

#376 ADAPT-5020 | @rebeccahongsf | form adjustments
  src/components/embed/giveGabForm.js
  static/scripts/travel-study/gg-form.css
  static/scripts/travel-study/gg-form.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#378 ADAPT-5020 | @rebeccahongsf | adjust internal form theme
  static/scripts/travel-study/gg-form.css
  static/scripts/travel-study/gg-form.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature
