Repository SU-SWS/saa_alumni, pull requests merged in 2022-02, with the labels that each got.

#276 ADAPT-4280: Theme localist widget
  gatsby-browser.js
  src/assets/arrow-right.svg
  src/assets/calendar.svg
  src/styles/localist.css
Labels: size/xs

#282 ADAPT-000: Redirect hardwire
  plugins/netlify-plugin-wildcard-404-redirect/index.js
Labels: size/xs

#288 ADAPT-4381: Adjusted og:titles for Travel Study pages.
  src/components/partials/seo.js
Labels: size/xs

#281 ADAPT-4307: Added unsafe-eval to Netlify security policy to allow AdPlugg embeds.
  netlify.toml
Labels: size/xs

#287 ADAPT-4415 | @rebeccahongsf | create sb protected page-type
  .babelrc
  gatsby-browser.js
  lambda/auth.js
  netlify.toml
  package-lock.json
  package.json
  plugins/netlify-plugin-vault-variables/index.js
  plugins/netlify-plugin-vault-variables/script.js
  plugins/netlify-plugin-wildcard-404-redirect/index.js
  src/components/auth/AuthIdleTimeoutOverlay.js
  src/components/auth/AuthenticatedPage.js
  src/components/components.js
  src/components/identity/masthead.js
  src/components/layout/Modal/Modal.styles.js
  src/components/navigation/UtilityNav.jsx
  src/components/navigation/accountLinks.js
  src/components/page-types/protectedPage.js
  src/components/search/openSearchModalButton.js
  src/contexts/AuthContext.js
  src/hooks/useTimer.js
  src/pages/protected-page.js
  src/utilities/getSiteUrl.js
  src/utilities/pluralize.js
Labels: size/xl, feature, patch

#283 ADAPT-3897: Accordeon component
  src/components/components.js
  src/components/composite/accordion.js
  src/components/composite/accordionItem.js
Labels: size/s

#289 Release V0.2.5
  README.md
  example.env
  gatsby-browser.js
  gatsby-config.js
  netlify.toml
  package-lock.json
  package.json
  plugins/netlify-plugin-vault-variables/README.md
  plugins/netlify-plugin-vault-variables/index.js
  plugins/netlify-plugin-vault-variables/manifest.yml
  plugins/netlify-plugin-vault-variables/package.json
  plugins/netlify-plugin-vault-variables/script.js
  src/assets/arrow-right.svg
  src/assets/calendar.svg
  src/components/cards/saaStoryCard.js
  src/components/components.js
  src/components/content-types/story/storyCardView.js
  src/components/partials/seo.js
  src/styles/localist.css
  static/_redirects
Labels: size/xl, patch

#295 Hotfix: use existing isTravelStudy variable for pathname check for ogTitle
  src/components/partials/seo.js
Labels: size/xs, patch, fix

#285 ADAPT-4388: Update gatsby netlify plugin
  netlify.toml
  package-lock.json
  package.json
Labels: size/l, patch

#291 ADAPT-4434 | @rebeccahongsf | explore and test gatsby client (api) routes
  .babelrc
  netlify.toml
  package-lock.json
  package.json
  static/_redirects
Labels: size/xs, feature, patch

#298 ADAPT-4173: Refactored callback to account for breaking change in adapt-auth-sdk.
  lambda/auth.js
  package-lock.json
  package.json
Labels: size/xl, patch

#299 ADAPT-4435 | @rebeccahongsf | clone gateway auth
  package-lock.json
  package.json
  src/utilities/ApiGatewayAuth.js
Labels: size/xs, feature, patch
