Repository SU-SWS/saa_alumni, pull requests merged in 2022-08, with the labels that each got.

#419 ADAPT-5214 | @rebeccahongsf | add format date functions
  src/components/page-types/formPage/formPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/utilities/transformDate.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#420 Release V1.0.4
  src/components/identity/GlobalHeader/GlobalHeader.styles.js
  src/components/navigation/accountLinks.js
  src/styles/global.css
Labels: patch

#407 ADAPT-5012 | @rebeccahongsf | fix up registration interstitial page style
  src/components/page-types/formPage/tripCustomJourneys.styles.js
  src/components/page-types/formPage/tripNotifyMe.styles.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/tripTravelerCard.js
  src/components/page-types/registrationFormPage/tripTravelerList.js
  src/components/page-types/registrationFormPage/tripTravelerListItem.js
Labels: feature

#421 ADAPT-5141 | @rebeccahongsf | update form styles
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/formPage.styles.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/interstitialPage.styles.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.styles.js
  src/styles/forms.css
Labels: feature

#424 ADAPT-5141 | @rebeccahongsf | registration form fixes
  src/components/embed/giveGabForm.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.styles.js
  src/styles/forms.css
Labels: feature

#426 ADAPT-5141 | @rebeccahongsf | form fixes
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/formPage.styles.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/styles/forms.css
Labels: feature

#425 ADAPT-5195 | @rebeccahongsf | conditionally extend loader duration
  src/components/embed/dynaScript.js
  src/components/embed/giveGabForm.js
Labels: feature

#427 ADAPT-5139 | @rebeccahongsf | staff form fixes
  src/styles/forms.css
  static/scripts/travel-study/gg-form.css
  static/scripts/travel-study/gg-form.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#428 ADAPT-5229 | @rebeccahongsf | update confirmation message styles
  src/components/embed/giveGabForm.js
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/formPage.styles.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.styles.js
  src/styles/forms.css
  static/confirmation-msg/custom-journeys-form.html
  static/confirmation-msg/notify-form.html
  static/confirmation-msg/payment-form.html
  static/confirmation-msg/reg-form.html
  static/scripts/travel-study/gg-form.css
Labels: feature

#429 ADAPT-5139 | @rebeccahongsf | update loading animation and form styles
  src/styles/forms.css
  static/scripts/travel-study/gg-form.css
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#431 ADAPT-5232 | @rebeccahongsf | add trip deposit fields and update trips api
  src/api/travel-study/reg/post-extension.js
  src/api/travel-study/reg/pre-extension.js
  src/api/travel-study/reg/trip-deposit.js
  src/api/travel-study/trips/index.js
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registationFormOptions.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#432 ADAPT-5232 | @rebeccahongsf | fix registration type
  src/api/travel-study/reg/trip-deposit.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#433 ADAPT-5141 | @rebeccahongsf | fix registration
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#438 ADAPT-5285 | @rebeccahongsf | add conditional check for pre/post ext dates
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#267 ADAPT-4096: Use v2 storyblok
  README.md
  dev/localhost-key.pem
  dev/localhost.pem
  package-lock.json
  package.json
  src/pages/editor.js
Labels: size/s, patch

#440 Release V1.1.0
  README.md
  dev/localhost-key.pem
  dev/localhost.pem
  package-lock.json
  package.json
  src/components/layout/ProtectedContentWrapper.jsx
  src/pages/editor.js
Labels: minor

#441 ADAPT-4686 | @rebeccahongsf | revert extensionOptions label
  src/api/travel-study/reg/post-extension.js
  src/api/travel-study/reg/pre-extension.js
Labels: feature

#437 ADAPT-5271 | @rebeccahongsf | add anchor listener for successful submission
  src/components/embed/dynaScript.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  static/scripts/travel-study/gg-form.js
  static/scripts/travel-study/gg-trip-form.js
Labels: feature

#442 ADAPT-5300 | @rebeccahongsf | update primary registrant and unique id
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#423 ADAPT-4686 | @rebeccahongsf | rework remove button toggle
  src/components/page-types/registrationFormPage/tripTravelerCard.js
  src/contexts/FormContext.js
Labels: feature

#445 ADAPT-5303 | @rebeccahongsf | conditionally display room category questions
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: feature

#446 ADAPT-5257 | @rebeccahongsf | enforce primary registrant to always attend trip
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/tripPrimaryCard.js
  src/components/page-types/registrationFormPage/tripTravelerList.js
  src/components/page-types/registrationFormPage/tripTravelerListItem.js
  src/contexts/FormContext.js
Labels: feature

#448 ADAPT-5341 | @rebeccahongsf | update dob func
  src/utilities/transformDate.js
Labels: feature

#447 ADAPT-5330 | @rebeccahongsf | update interstitial and form styling
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPageExtensionSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/formPage/formPage.styles.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/interstitialPage.styles.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/tripPrimaryCard.js
  src/components/page-types/registrationFormPage/tripTravelerCard.js
  src/components/page-types/registrationFormPage/tripTravelerListItem.js
  src/styles/forms.css
Labels: feature

#449 ADAPT-5141 | @rebeccahongsf | update back to link style
  src/components/page-types/formPage/tripCustomJourneys.styles.js
  src/components/page-types/formPage/tripNotifyMe.styles.js
Labels: feature
