Repository SU-SWS/saa_alumni, pull requests merged in 2022-01, with the labels that each got.

#268 ADAPT-4209: Add 0.4" print margin to Trip Page
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPage.styles.js
Labels: size/xs, patch, task

#264 ADAPT-3993: Filter out the past trips
  gatsby-node.js
  src/hooks/useTrips.js
Labels: size/xs

#270 ADAPT-4224: Redirect for trusteenominations
  static/_redirects
Labels: size/xs

#272 Release 0.2.4
  gatsby-node.js
  src/components/page-types/TripPage/TripPage.jsx
  src/components/page-types/TripPage/TripPage.styles.js
  src/hooks/useTrips.js
  src/utilities/filterTrips.js
  static/_redirects
Labels: size/xs, patch

#269 ADAPT-4222: Updating redirects with new locations
  static/_redirects
Labels: size/xs

#274 ADAPT-4216: Port Vault variable management strategy.
  README.md
  example.env
  gatsby-config.js
  netlify.toml
  package-lock.json
  package.json
  plugins/netlify-plugin-vault-variables/README.md
  plugins/netlify-plugin-vault-variables/index.js
  plugins/netlify-plugin-vault-variables/manifest.yml
  plugins/netlify-plugin-vault-variables/package.json
  plugins/netlify-plugin-vault-variables/script.js
Labels: size/xl, patch, task

#279 Update README.md so it's clearer
  README.md
Labels: size/xs

#273 ADAPT-3834: Manual story card
  src/components/cards/saaStoryCard.js
  src/components/components.js
  src/components/content-types/story/storyCardView.js
Labels: size/m
