Repository SU-SWS/saa_alumni, pull requests merged in 2022-10, with the labels that each got.

#478 ADAPT-5426 | @rebeccahongsf | further specify radio button styling
  src/styles/forms.css
Labels: fix

#479 ADAPT-5410 | @jdwjdwjdw | protect against missing body value
  src/components/search/searchResults.js
Labels: fix

#480 ADAPT-5318 | @jdwjdwjdw | Exclude form pages from sitemap
  gatsby-config.js
Labels: task

#477 ADAPT-5438 | @rebeccahongsf | resolve scroll bug on reg pages
  gatsby-browser.js
  src/components/embed/dynaScript.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
Labels: fix

#481 Release v2.0.5
  gatsby-browser.js
  gatsby-config.js
  src/api/travel-study/reg/trip-deposit.js
  src/components/embed/dynaScript.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/search/searchResults.js
  src/styles/forms.css
Labels: patch

#482 ADAPT-5438 | @rebeccahongsf | add scroll to top for discard registrant scenario
  src/components/embed/dynaScript.js
Labels: feature

#484 NoJira: Package updates for security release.
  package-lock.json
  package.json
Labels: patch

#485 Release: v2.0.6
  package-lock.json
  package.json
  src/components/embed/dynaScript.js
Labels: patch

#487 NOJIRA | @rebeccahongsf | hide remove btn for primary reg
  src/styles/forms.css
Labels: feature

#486 EXRESUPP-48 | @rebeccahongsf | add conditional to gatsby node for unpublished trips
  gatsby-node.js
Labels: fix

#488 NOJIRA | @rebeccahongsf | fixup remove btn styles
  src/styles/forms.css
Labels: feature

#489 Release: v2.0.7
  gatsby-node.js
  src/styles/forms.css
Labels: patch

#490 NOJIRA | @rebeccahongsf | resolve specific use case bug
  src/styles/forms.css
Labels: fix

#494 NOJIRA | @rebeccahongsf | resolve missing hero gradient
  src/components/composite/HeroImage/HeroImage.jsx
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/embed/giveGabForm.js
  src/styles/forms.css
Labels: feature

#496 Release: v2.0.9
  src/components/composite/HeroImage/HeroImage.jsx
  src/components/composite/HeroImage/HeroImage.styles.js
  src/components/embed/giveGabForm.js
  src/styles/forms.css
Labels: patch

#497 EXRESUPP-45 | @jdwjdwjdw | Search for term with missing content value causes WSOD
  src/components/search/searchResults.js
Labels: fix

#500 Release/v2.0.10
  src/components/search/searchResults.js
  src/styles/forms.css
Labels: patch
