Repository SU-SWS/saa_alumni, pull requests merged in 2022-04, with the labels that each got.

#312 ADAPT-4539: Protected content
  gatsby-node.js
  package-lock.json
  package.json
  src/api/private-proxy.js
  src/components/cards/promoCodeBanner.js
  src/components/cards/protectedContentItem.js
  src/components/components.js
  src/components/layout/ProtectedContentWrapper.jsx
  src/components/simple/heroIcon.js
Labels: size/s, patch

#325 ADAPT-4552: Affiliation checking for authenticated content.
  README.md
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/api/private-proxy.js
  src/components/layout/ProtectedContentWrapper.jsx
  src/utilities/MegaProfile.js
  src/utilities/mockServer.js
  src/utilities/mocks/affiliations.js
  src/utilities/mocks/contact.js
  src/utilities/mocks/index.js
Labels: size/m, patch

#322 ADAPT-4416 | @rebeccahongsf | theme form page-type component
  gatsby-config.js
  src/components/components.js
  src/components/page-types/formPage/formPage.js
  src/components/page-types/formPage/tripCustomJourneys.js
  src/components/page-types/formPage/tripNotifyMe.js
Labels: size/s, feature

#321 ADAPT-4469: Payment form theming
  gatsby-browser.js
  src/assets/arrow-down.svg
  src/components/embed/giveGabForm.js
  src/styles/forms.css
Labels: size/s

#323 ADAPT-4674 | @rebeccahongsf | registration page poc
  gatsby-config.js
  gatsby-node.js
  src/api/auth/profile.js
  src/components/components.js
  src/components/embed/giveGabForm.js
  src/components/page-types/formPage/interstitialPage.js
  src/components/page-types/formPage/registrationFormPage.js
  src/components/page-types/formPage/tripRelationshipCard.js
  src/components/page-types/formPage/tripRelationshipList.js
  src/components/page-types/formPage/tripRelationshipListItem.js
  src/contexts/FormContext.js
  src/templates/storyblok-entry.js
Labels: size/l, feature

#331 ADAPT-4873: Perks branch refactoring
  .github/workflows/pr-labeler.yml
  gatsby-ssr.js
  package-lock.json
  package.json
  src/api/auth/login.js
  src/api/auth/profile.js
  src/api/private-proxy.js
  src/components/components.js
  src/components/embed/dynaScript.js
  src/components/embed/giveGabForm.js
  src/components/layout/ProtectedContentWrapper.jsx
  src/components/navigation/accountLinks.js
  src/contexts/AuthContext.js
  src/utilities/ApiGatewayAuth.js
  src/utilities/MegaProfile.js
  src/utilities/getGgProfile.js
  src/utilities/giveGabVars.js
  src/utilities/mockServer.js
  src/utilities/mocks/contact.js
  src/utilities/mocks/fullgg.js
  src/utilities/mocks/index.js
Labels: size/xl, patch

#332 ADAPT-4909: Redirect young alumni
  static/_redirects
Labels: size/xs
