Repository SU-SWS/saa_alumni, pull requests merged in 2022-09, with the labels that each got.

#450 ADAPT-5355 | @rebeccahongsf | update interstitial page copy
  src/components/page-types/registrationFormPage/interstitialPage.js
Labels: feature

#452 ADAPT-4686 | @rebeccahongsf | tsgg cleanup
  README.md
  package-lock.json
  package.json
  src/components/page-types/formPage/tripCustomJourneys.js
  src/components/page-types/formPage/tripNotifyMe.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/utilities/giveGabVars.js
  static/test-custom-journeys.html
  static/test-notify-me.html
  static/test-registration.html
Labels: feature, patch

#456 Release v2.0.1
  package.json
  src/api/auth/profile.js
  src/contexts/AuthContext.js
Labels: patch

#460 ADAPT-5375 | Itinerary last item should display accommodation and meals
  src/components/composite/itineraryItem.js
Labels: fix

#461 Release/v.2.0.2
  README.md
  package.json
  src/components/composite/itineraryItem.js
Labels: patch

#458 ADAPT-5355 and ADAPT-5360s series | @rebeccahongsf | bulk tsgg updates
  src/api/travel-study/index.js
  src/api/travel-study/reg/post-extension.js
  src/api/travel-study/reg/pre-extension.js
  src/components/cta/SAALinkButton.jsx
  src/components/embed/dynaScript.js
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.styles.js
  src/components/page-types/TripPage/TripPagePricingSection.jsx
  src/components/page-types/TripPage/TripPageSectionNav.jsx
  src/components/page-types/TripPage/TripPageSectionNav.styles.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/tripTravelerList.js
  src/styles/forms.css
Labels: feature

#465 ADAPT-5425 | @rebeccahongsf | fix email and phone number types logic
  src/components/page-types/registrationFormPage/registationFormOptions.js
  src/components/page-types/registrationFormPage/tripTravelerList.js
  src/utilities/giveGabVars.js
  src/utilities/mocks/fullgg.js
Labels: feature

#468 Release/v2.0.3
  src/api/travel-study/index.js
  src/api/travel-study/reg/post-extension.js
  src/api/travel-study/reg/pre-extension.js
  src/components/cards/TripCard/TripCard.jsx
  src/components/composite/itineraryItem.js
  src/components/cta/SAALinkButton.jsx
  src/components/embed/dynaScript.js
  src/components/page-types/TripPage/TripPageOverviewSection.jsx
  src/components/page-types/TripPage/TripPageOverviewSection.styles.js
  src/components/page-types/TripPage/TripPagePricingSection.jsx
  src/components/page-types/TripPage/TripPageSectionNav.jsx
  src/components/page-types/TripPage/TripPageSectionNav.styles.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/components/page-types/registrationFormPage/registationFormOptions.js
  src/components/page-types/registrationFormPage/registrationFormPage.js
  src/components/page-types/registrationFormPage/tripTravelerList.js
  src/styles/forms.css
  src/utilities/giveGabVars.js
  src/utilities/mocks/fullgg.js
Labels: patch

#469 ADAPT-5425 | @rebeccahongsf | resolve email type issue
  src/utilities/giveGabVars.js
Labels: feature

#470 ADAPT-5426 | @rebeccahongsf | fixup email type
  src/utilities/giveGabVars.js
  src/utilities/mocks/fullgg.js
Labels: feature

#472 Release v2.0.4
  src/pages/editor.js
  src/utilities/giveGabVars.js
  src/utilities/mocks/fullgg.js
Labels: patch

#473 ADAPT-5440 | @rebeccahongsf | update email type styling
  src/styles/forms.css
Labels: feature

#474 ADAPT-5439 | @rebeccahongsf | remove deposit from reg types
  src/api/travel-study/reg/trip-deposit.js
  src/components/page-types/registrationFormPage/interstitialPage.js
Labels: feature
