Repository SU-SWS/saa_alumni, pull requests merged in 2024-07, with the labels that each got.

#880 Release v4.4.5
  gatsby-node.js
  static/_redirects
Labels: patch

#882 DS-709, DS-710, DS-712 | @ericbakenhus | Add tag and region filters
  src/components/content-types/synchronized-event/synchronizedEvent.js
  src/components/events-discovery/components/Event/Event.jsx
  src/components/events-discovery/components/Event/EventHeading.jsx
  src/components/events-discovery/components/Facets/FacetCtx.jsx
  src/components/events-discovery/components/Filters/DesktopFilter.jsx
  src/components/events-discovery/components/Hit/Hit.jsx
  src/components/events-discovery/components/LocationFilter/InternationalSubfilter.jsx
  src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
  src/components/events-discovery/components/LocationFilter/UsSubfilter.jsx
  src/components/events-discovery/components/LocationFilter/index.js
  src/components/events-discovery/components/SubjectFilter/GeneralTagsFilter.jsx
  src/components/events-discovery/components/SubjectFilter/IdentityTagsFilter.jsx
  src/components/events-discovery/components/SubjectFilter/SubjectFilter.jsx
  src/components/events-discovery/components/SubjectFilter/index.js
  src/components/events-discovery/components/constants.js
Labels: retro

#884 DS-721 | @ericbakenhus | Add results count
  src/components/events-discovery/components/Chips/Chip.jsx
  src/components/events-discovery/components/DateFilter/DateFilter.jsx
  src/components/events-discovery/components/Event/Event.jsx
  src/components/events-discovery/components/Event/EventContent.jsx
  src/components/events-discovery/components/StatusHeader/StatusHeader.jsx
  src/components/events-discovery/eventsDiscovery.jsx
Labels: retro

#885 DS-714 | @ericbakenhus | Search bar with autocomplete
  package-lock.json
  package.json
  src/components/events-discovery/components/Chips/ChipsComponent.jsx
  src/components/events-discovery/components/FilterAccordion/FilterAccordion.jsx
  src/components/events-discovery/components/Filters/DesktopFilter.jsx
  src/components/events-discovery/components/SearchBar/SearchBar.jsx
  src/components/events-discovery/components/SearchBar/index.js
  src/components/events-discovery/components/constants.js
  src/components/events-discovery/eventsDiscovery.jsx
  src/hooks/useDebouncedValue.js
Labels: retro

#886 DS-793 | @ericbakenhus | Allow switching timezones on events
  src/components/events-discovery/components/Event/Event.jsx
  src/components/events-discovery/components/Event/EventContent.jsx
  src/components/events-discovery/components/Hit/Hit.jsx
Labels: retro

#888 DS-722 | @ericbakenhus | Add title highlighting
  src/components/events-discovery/components/Event/Event.jsx
  src/components/events-discovery/components/Event/EventHeading.jsx
  src/components/events-discovery/components/Hit/Hit.jsx
Labels: retro

#889 DS-793 | @ericbakenhus | Handle when different timezones with the same offset
  src/components/events-discovery/components/Event/EventContent.jsx
Labels: retro

#890 DS-793 | @ericbakenhus | Tweak timezone format
  src/components/events-discovery/components/Event/EventContent.jsx
Labels: retro

#891 DS-800 | @ericbakenhus | Misc QA fixes
  src/components/events-discovery/components/Filters/DesktopFilter.jsx
Labels: retro

#892 Release/v4.5.0
  package-lock.json
  package.json
  src/components/components.js
  src/components/media/imageGallery.js
  src/styles/sb-image-gallery.css
Labels: minor

#893 DS-800 | @ericbakenhus | Adjust filters
  src/components/events-discovery/components/Chips/Chip.jsx
  src/components/events-discovery/components/Chips/Chips.jsx
  src/components/events-discovery/components/Chips/index.js
  src/components/events-discovery/components/Facets/FacetComponent.jsx
  src/components/events-discovery/components/Facets/FacetCtx.jsx
  src/components/events-discovery/components/Facets/FacetList.jsx
  src/components/events-discovery/components/Facets/index.js
  src/components/events-discovery/components/Facets/useFacets.js
  src/components/events-discovery/components/FilterAccordion/FilterAccordion.jsx
  src/components/events-discovery/components/FilterAccordion/SubfilterAccordion.jsx
  src/components/events-discovery/components/FilterAccordion/index.js
  src/components/events-discovery/components/Filters/DesktopFilter.jsx
  src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
  src/components/events-discovery/components/LocationFilter/OnlineOptionsSubfilter.jsx
  src/components/events-discovery/components/LocationFilter/UsSubfilter.jsx
  src/components/events-discovery/components/SubjectFilter/GeneralTagsFilter.jsx
  src/components/events-discovery/components/SubjectFilter/IdentityTagsFilter.jsx
  src/components/events-discovery/components/SubjectFilter/SubjectFilter.jsx
  src/components/events-discovery/components/constants.js
  src/components/events-discovery/eventsDiscovery.jsx
Labels: retro

#895 DS-800 | @ericbakenhus | Results per page
  src/components/events-discovery/components/Chips/Chip.jsx
  src/components/events-discovery/components/Event/EventContent.jsx
  src/components/events-discovery/components/EventsPerPage/EventsPerPage.jsx
  src/components/events-discovery/components/EventsPerPage/index.js
  src/components/events-discovery/components/Facets/FacetCtx.jsx
  src/components/events-discovery/components/Facets/FacetList.jsx
  src/components/events-discovery/eventsDiscovery.jsx
Labels: retro

#896 DS-800 | @ericbakenhus | Adjust labels
  src/components/events-discovery/components/Facets/FacetCtx.jsx
  src/components/events-discovery/components/Facets/FacetList.jsx
  src/components/events-discovery/components/Filters/DesktopFilter.jsx
  src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
Labels: retro
