Repository SU-SWS/saa_alumni, pull requests merged in 2024-09, with the labels that each got.

#944 Release v5.0.4
  netlify/functions/event-import-background.mts
  netlify/functions/trigger-event-import.mts
  src/components/events-discovery/components/Event/EventContent.jsx
  src/components/events-discovery/components/EventsPerPage/EventsPerPage.jsx
  src/components/events-discovery/components/LocationFilter/LocationTabPanelCity.jsx
  src/components/partials/header.js
  src/utilities/synchronizedEvents.js
Labels: patch

#952 Release v5.0.5
  src/utilities/dates.js
  src/utilities/transformDate.js
Labels: patch

#937 DS-735 | @ericbakenhus | Event Cards
  src/components/components.js
  src/components/content-types/synchronized-event/SynchronizedEventCard.jsx
  src/components/content-types/synchronized-event/synchronizedEvent.jsx
  src/components/content-types/synchronized-event/synchronizedEventCardList.jsx
  src/components/events-discovery/components/Event/Event.jsx
  src/components/events-discovery/components/Event/EventContent.jsx
  src/components/events-discovery/components/Event/EventHeading.jsx
  src/hooks/useEvents.js
Labels: retro

#958 DS-800 | @ericbakenhus | Filter wrapping fix
  src/components/events-discovery/components/Facets/FacetList.jsx
Labels: fix

#959 DS-735 | @ericbakenhus | Stretch link for event cards
  src/components/content-types/synchronized-event/SynchronizedEventCard.jsx
  src/components/events-discovery/components/Event/EventContent.jsx
Labels: retro

#961 Release v5.1.0
  .gitignore
  package-lock.json
  package.json
  src/api/walletpass/android.js
  src/api/walletpass/ios.js
  src/components/components.js
  src/components/content-types/synchronized-event/SynchronizedEventCard.jsx
  src/components/content-types/synchronized-event/synchronizedEvent.jsx
  src/components/content-types/synchronized-event/synchronizedEventCardList.jsx
  src/components/events-discovery/components/Chips/Chip.jsx
  src/components/events-discovery/components/DateFilter/DateFilter.jsx
  src/components/events-discovery/components/DateFilter/MobileDateFilter.jsx
  src/components/events-discovery/components/Event/Event.jsx
  src/components/events-discovery/components/Event/EventContent.jsx
  src/components/events-discovery/components/Event/EventHeading.jsx
  src/components/events-discovery/components/EventsPerPage/EventsPerPage.jsx
  src/components/events-discovery/components/Facets/FacetCtx.jsx
  src/components/events-discovery/components/Facets/FacetList.jsx
  src/components/events-discovery/components/Facets/MobileFacetList.jsx
  src/components/events-discovery/components/FilterAccordion/FilterAccordion.jsx
  src/components/events-discovery/components/Filters/MobileFilter.jsx
  src/components/events-discovery/components/Filters/MobileFilterFooter.jsx
  src/components/events-discovery/components/Filters/MobileFilterHeader.jsx
  src/components/events-discovery/components/Filters/MobileParentFilter.jsx
  src/components/events-discovery/components/LocationFilter/LocationTabPanelCity.jsx
  src/components/events-discovery/components/SearchBar/MobileSearchBar.jsx
  src/components/events-discovery/components/SearchBar/SearchBar.jsx
  src/components/events-discovery/components/StatusHeader/StatusHeader.jsx
  src/components/wallet/walletPass.js
  src/hooks/useEvents.js
  src/images/android-wallet-badge.svg
  src/images/apple-wallet-badge.svg
  src/utilities/walletPass.js
Labels: minor

#963 Release/v5.1.1
  src/components/wallet/walletPass.js
  src/utilities/walletPass.js
Labels: patch

#965 Release v5.1.2
  src/components/events-discovery/components/DateFilter/RadioInput.jsx
Labels: patch

#966 Nojira | @ericbakenhus | Fix mobile filter text color
  src/components/events-discovery/components/Facets/MobileFacetList.jsx
  src/components/events-discovery/components/Filters/MobileParentFilter.jsx
Labels: fix

#967 Release v5.1.3
  src/components/events-discovery/components/Facets/MobileFacetList.jsx
  src/components/events-discovery/components/Filters/MobileParentFilter.jsx
Labels: patch

#971 Nojira | @ericbakenhus | Scroll to heading on event pagination change
  src/components/events-discovery/components/Pagination/Pagination.jsx
  src/components/events-discovery/components/StatusHeader/StatusHeader.jsx
Labels: retro

#972 Release v5.1.4
  src/components/events-discovery/components/Pagination/Pagination.jsx
  src/components/events-discovery/components/StatusHeader/StatusHeader.jsx
  src/components/navigation/MegaMenu/megaMenuLink.styles.js
  src/components/navigation/MegaMenu/megaMenuTopLevelLinkItem.js
Labels: patch

#975 Nojira | @ericbakenhus | Fix deploy
  netlify/functions/handle-deploy.mts
Labels: retro

#974 Release v5.1.5
  netlify/functions/handle-deploy.mts
  src/api/travel-study/index.js
  src/api/travel-study/reg/internal-deposit.js
  src/api/travel-study/reg/post-extension.js
  src/api/travel-study/reg/pre-extension.js
  src/api/travel-study/reg/room-category.js
  src/api/travel-study/reg/trip-deposit.js
  src/api/travel-study/trips/index.js
  src/components/events-discovery/components/Facets/FacetList.jsx
  src/components/events-discovery/components/SearchBar/MobileSearchBar.jsx
  src/components/events-discovery/components/SearchBar/SearchBar.jsx
  src/components/events-discovery/eventsDiscovery.jsx
  src/utilities/getAllTrips.js
Labels: patch
