Repository SU-SWS/saa_alumni, pull requests merged in 2024-10, with the labels that each got.

#983 Release/v5.1.6
  netlify/functions/event-import-background.mts
Labels: patch, retro

#987 DS-1011 | @ericbakenhus | Fix date parsing function
  src/components/page-types/membershipFormPage/relatedContactSelection.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/utilities/transformDate.js
  src/utilities/userProfile.js
Labels: retro

#988 Release v5.1.7
  src/components/page-types/membershipFormPage/relatedContactSelection.js
  src/components/page-types/registrationFormPage/interstitialPage.js
  src/utilities/transformDate.js
  src/utilities/userProfile.js
Labels: patch

#991 Release v5.1.8
  src/components/events-discovery/components/Event/EventContent.jsx
Labels: patch
