Repository SU-SWS/saa_alumni, pull requests merged in 2024-08, with the labels that each got.

#905 DS-800 | @ericbakenhus | Show more
  src/components/events-discovery/components/Facets/FacetList.jsx
  src/components/events-discovery/components/Facets/MobileFacetList.jsx
Labels: retro

#921 Release v5.0.1
  src/components/events-discovery/components/Facets/FacetList.jsx
  src/components/events-discovery/components/Facets/MobileFacetList.jsx
  src/components/events-discovery/components/LocationFilter/LocationFilter.jsx
Labels: patch

#923 DS-800 | @ericbakenhus | No context var for scheduled functions
  netlify/functions/trigger-event-import.mts
Labels: retro

#924 Release v5.0.2
  netlify/functions/trigger-event-import.mts
Labels: patch

#927 Nojira | @ericbakenhus | Use siteUrl for base URL in SSR
  src/components/navigation/MegaMenu/megaMenuTopLevelLinkItem.js
Labels: fix

#928 Release: v5.0.3
  src/components/navigation/MegaMenu/megaMenuTopLevelLinkItem.js
Labels: patch
